nixPkgs = ["nodejs","npm"]

[phases.strapi-install]
cmds = ["npm install"]
onlyIncludeFiles = ["strapi/"]

[phases.sveltekit-install]
cmds = ["npm install"]
onlyIncludeFiles = ["sveltekit/"]

[start]
cmd = "./start.sh"