nixPkgs = ["nodejs"]

[phases.strapi-install]
cmds = ["npm install"]
onlyIncludeFiles = ["strapi/"]

[phases.sveltekit-install]
cmds = ["npm install"]
onlyIncludeFiles = ["sveltekit/"]

[start.strapi]
cmd = "npm --prefix ./strapi run start"
onlyIncludeFiles = ["strapi/"]

[start.sveltekit]
cmd = "npm --prefix ./sveltekit run dev"
onlyIncludeFiles = ["sveltekit/"]