[phases.setup]
nixPkgs = ['nodejs-18_x'] 

[phases.strapi-install]
cmds = ['npm install']
onlyIncludeFiles = ['strapi/']

[phases.sveltekit-install]  
cmds = ['npm install']
onlyIncludeFiles = ['sveltekit/']

[start.strapi]
cmd = "npm run start"
onlyIncludeFiles = ['strapi/']

[start.sveltekit]
cmd = "npm run dev" 
onlyIncludeFiles = ['sveltekit/']