/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BookingsPost201ResponseInner,
  ChannelsBookingPostRequestInner,
} from '../models/index';
import {
    BookingsPost201ResponseInnerFromJSON,
    BookingsPost201ResponseInnerToJSON,
    ChannelsBookingPostRequestInnerFromJSON,
    ChannelsBookingPostRequestInnerToJSON,
} from '../models/index';

export interface ChannelsBookingPostRequest {
    channelsBookingPostRequestInner?: Array<ChannelsBookingPostRequestInner>;
}

/**
 * 
 */
export class ChannelsBookingComApi extends runtime.BaseAPI {

    /**
     * Under construction - Perform actions at Booking.com
     */
    async channelsBookingPostRaw(requestParameters: ChannelsBookingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BookingsPost201ResponseInner>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = await this.configuration.apiKey("token"); // token authentication
        }

        const response = await this.request({
            path: `/channels/booking`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.channelsBookingPostRequestInner.map(ChannelsBookingPostRequestInnerToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BookingsPost201ResponseInnerFromJSON));
    }

    /**
     * Under construction - Perform actions at Booking.com
     */
    async channelsBookingPost(requestParameters: ChannelsBookingPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BookingsPost201ResponseInner>> {
        const response = await this.channelsBookingPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
