/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WebhooksBookingsPostRequest,
} from '../models/index';
import {
    WebhooksBookingsPostRequestFromJSON,
    WebhooksBookingsPostRequestToJSON,
} from '../models/index';

export interface WebhooksBookingsPostOperationRequest {
    webhooksBookingsPostRequest?: WebhooksBookingsPostRequest;
}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI {

    /**
     * Configure under Settings -> Properties -> Access -> Booking Webhook
     * Under construction - The webhook payload sent to your URL
     */
    async webhooksBookingsPostRaw(requestParameters: WebhooksBookingsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = await this.configuration.apiKey("token"); // token authentication
        }

        const response = await this.request({
            path: `/Webhooks - bookings`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebhooksBookingsPostRequestToJSON(requestParameters.webhooksBookingsPostRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Configure under Settings -> Properties -> Access -> Booking Webhook
     * Under construction - The webhook payload sent to your URL
     */
    async webhooksBookingsPost(requestParameters: WebhooksBookingsPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.webhooksBookingsPostRaw(requestParameters, initOverrides);
    }

}
