/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AirbnbSettingsPostPropertiesInnerRoomTypesInner
 */
export interface AirbnbSettingsPostPropertiesInnerRoomTypesInner {
    /**
     * 
     * @type {boolean}
     * @memberof AirbnbSettingsPostPropertiesInnerRoomTypesInner
     */
    enabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AirbnbSettingsPostPropertiesInnerRoomTypesInner
     */
    id?: number;
}

/**
 * Check if a given object implements the AirbnbSettingsPostPropertiesInnerRoomTypesInner interface.
 */
export function instanceOfAirbnbSettingsPostPropertiesInnerRoomTypesInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AirbnbSettingsPostPropertiesInnerRoomTypesInnerFromJSON(json: any): AirbnbSettingsPostPropertiesInnerRoomTypesInner {
    return AirbnbSettingsPostPropertiesInnerRoomTypesInnerFromJSONTyped(json, false);
}

export function AirbnbSettingsPostPropertiesInnerRoomTypesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AirbnbSettingsPostPropertiesInnerRoomTypesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function AirbnbSettingsPostPropertiesInnerRoomTypesInnerToJSON(value?: AirbnbSettingsPostPropertiesInnerRoomTypesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
        'id': value.id,
    };
}

