/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InvoiceItem } from './InvoiceItem';
import {
    InvoiceItemFromJSON,
    InvoiceItemFromJSONTyped,
    InvoiceItemToJSON,
} from './InvoiceItem';

/**
 * 
 * @export
 * @interface BookingsInvoicesGet200ResponseAllOfDataInner
 */
export interface BookingsInvoicesGet200ResponseAllOfDataInner {
    /**
     * 
     * @type {number}
     * @memberof BookingsInvoicesGet200ResponseAllOfDataInner
     */
    invoiceId?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof BookingsInvoicesGet200ResponseAllOfDataInner
     */
    invoiceDate?: Date | null;
    /**
     * 
     * @type {Array<InvoiceItem>}
     * @memberof BookingsInvoicesGet200ResponseAllOfDataInner
     */
    invoiceItems?: Array<InvoiceItem>;
}

/**
 * Check if a given object implements the BookingsInvoicesGet200ResponseAllOfDataInner interface.
 */
export function instanceOfBookingsInvoicesGet200ResponseAllOfDataInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookingsInvoicesGet200ResponseAllOfDataInnerFromJSON(json: any): BookingsInvoicesGet200ResponseAllOfDataInner {
    return BookingsInvoicesGet200ResponseAllOfDataInnerFromJSONTyped(json, false);
}

export function BookingsInvoicesGet200ResponseAllOfDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingsInvoicesGet200ResponseAllOfDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'invoiceId': !exists(json, 'invoiceId') ? undefined : json['invoiceId'],
        'invoiceDate': !exists(json, 'invoiceDate') ? undefined : (json['invoiceDate'] === null ? null : new Date(json['invoiceDate'])),
        'invoiceItems': !exists(json, 'invoiceItems') ? undefined : ((json['invoiceItems'] as Array<any>).map(InvoiceItemFromJSON)),
    };
}

export function BookingsInvoicesGet200ResponseAllOfDataInnerToJSON(value?: BookingsInvoicesGet200ResponseAllOfDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'invoiceId': value.invoiceId,
        'invoiceDate': value.invoiceDate === undefined ? undefined : (value.invoiceDate === null ? null : value.invoiceDate.toISOString().substring(0,10)),
        'invoiceItems': value.invoiceItems === undefined ? undefined : ((value.invoiceItems as Array<any>).map(InvoiceItemToJSON)),
    };
}

