/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookingAllOfInfoItems
 */
export interface BookingAllOfInfoItems {
    /**
     * 
     * @type {number}
     * @memberof BookingAllOfInfoItems
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof BookingAllOfInfoItems
     */
    createTime?: Date;
}

/**
 * Check if a given object implements the BookingAllOfInfoItems interface.
 */
export function instanceOfBookingAllOfInfoItems(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookingAllOfInfoItemsFromJSON(json: any): BookingAllOfInfoItems {
    return BookingAllOfInfoItemsFromJSONTyped(json, false);
}

export function BookingAllOfInfoItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingAllOfInfoItems {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createTime': !exists(json, 'createTime') ? undefined : (new Date(json['createTime'])),
    };
}

export function BookingAllOfInfoItemsToJSON(value?: BookingAllOfInfoItems | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createTime': value.createTime === undefined ? undefined : (value.createTime.toISOString()),
    };
}

