/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookingsMessagesPatchRequest
 */
export interface BookingsMessagesPatchRequest {
    /**
     * 
     * @type {boolean}
     * @memberof BookingsMessagesPatchRequest
     */
    read?: boolean;
}

/**
 * Check if a given object implements the BookingsMessagesPatchRequest interface.
 */
export function instanceOfBookingsMessagesPatchRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookingsMessagesPatchRequestFromJSON(json: any): BookingsMessagesPatchRequest {
    return BookingsMessagesPatchRequestFromJSONTyped(json, false);
}

export function BookingsMessagesPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingsMessagesPatchRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'read': !exists(json, 'read') ? undefined : json['read'],
    };
}

export function BookingsMessagesPatchRequestToJSON(value?: BookingsMessagesPatchRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'read': value.read,
    };
}

