/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CalendarCalendarInnerChannelsAgoda } from './CalendarCalendarInnerChannelsAgoda';
import {
    CalendarCalendarInnerChannelsAgodaFromJSON,
    CalendarCalendarInnerChannelsAgodaFromJSONTyped,
    CalendarCalendarInnerChannelsAgodaToJSON,
} from './CalendarCalendarInnerChannelsAgoda';

/**
 * Maximum number of bookings allowed for specific channels. Can be set to null to remove the limit.
 * @export
 * @interface CalendarCalendarInnerChannels
 */
export interface CalendarCalendarInnerChannels {
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    agoda?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    airbnb?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    asiatravel?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    atraveode?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    booking?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    despegar?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    edreamsodigeo?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    expedia?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    feratel?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    goibibo?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    hometogo?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    hostelworld?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    hotelbeds?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    hrs?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    jomres?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    marriott?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    ostrovokru?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    ota?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    reserva?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    tiket?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    tomastravel?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    traveloka?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    travia?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    traum?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    trip?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    tripadvisorrentals?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    vacationstay?: CalendarCalendarInnerChannelsAgoda;
    /**
     * 
     * @type {CalendarCalendarInnerChannelsAgoda}
     * @memberof CalendarCalendarInnerChannels
     */
    vrbo?: CalendarCalendarInnerChannelsAgoda;
}

/**
 * Check if a given object implements the CalendarCalendarInnerChannels interface.
 */
export function instanceOfCalendarCalendarInnerChannels(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CalendarCalendarInnerChannelsFromJSON(json: any): CalendarCalendarInnerChannels {
    return CalendarCalendarInnerChannelsFromJSONTyped(json, false);
}

export function CalendarCalendarInnerChannelsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CalendarCalendarInnerChannels {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'agoda': !exists(json, 'agoda') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['agoda']),
        'airbnb': !exists(json, 'airbnb') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['airbnb']),
        'asiatravel': !exists(json, 'asiatravel') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['asiatravel']),
        'atraveode': !exists(json, 'atraveode') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['atraveode']),
        'booking': !exists(json, 'booking') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['booking']),
        'despegar': !exists(json, 'despegar') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['despegar']),
        'edreamsodigeo': !exists(json, 'edreamsodigeo') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['edreamsodigeo']),
        'expedia': !exists(json, 'expedia') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['expedia']),
        'feratel': !exists(json, 'feratel') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['feratel']),
        'goibibo': !exists(json, 'goibibo') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['goibibo']),
        'hometogo': !exists(json, 'hometogo') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['hometogo']),
        'hostelworld': !exists(json, 'hostelworld') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['hostelworld']),
        'hotelbeds': !exists(json, 'hotelbeds') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['hotelbeds']),
        'hrs': !exists(json, 'hrs') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['hrs']),
        'jomres': !exists(json, 'jomres') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['jomres']),
        'marriott': !exists(json, 'marriott') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['marriott']),
        'ostrovokru': !exists(json, 'ostrovokru') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['ostrovokru']),
        'ota': !exists(json, 'ota') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['ota']),
        'reserva': !exists(json, 'reserva') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['reserva']),
        'tiket': !exists(json, 'tiket') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['tiket']),
        'tomastravel': !exists(json, 'tomastravel') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['tomastravel']),
        'traveloka': !exists(json, 'traveloka') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['traveloka']),
        'travia': !exists(json, 'travia') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['travia']),
        'traum': !exists(json, 'traum') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['traum']),
        'trip': !exists(json, 'trip') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['trip']),
        'tripadvisorrentals': !exists(json, 'tripadvisorrentals') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['tripadvisorrentals']),
        'vacationstay': !exists(json, 'vacationstay') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['vacationstay']),
        'vrbo': !exists(json, 'vrbo') ? undefined : CalendarCalendarInnerChannelsAgodaFromJSON(json['vrbo']),
    };
}

export function CalendarCalendarInnerChannelsToJSON(value?: CalendarCalendarInnerChannels | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'agoda': CalendarCalendarInnerChannelsAgodaToJSON(value.agoda),
        'airbnb': CalendarCalendarInnerChannelsAgodaToJSON(value.airbnb),
        'asiatravel': CalendarCalendarInnerChannelsAgodaToJSON(value.asiatravel),
        'atraveode': CalendarCalendarInnerChannelsAgodaToJSON(value.atraveode),
        'booking': CalendarCalendarInnerChannelsAgodaToJSON(value.booking),
        'despegar': CalendarCalendarInnerChannelsAgodaToJSON(value.despegar),
        'edreamsodigeo': CalendarCalendarInnerChannelsAgodaToJSON(value.edreamsodigeo),
        'expedia': CalendarCalendarInnerChannelsAgodaToJSON(value.expedia),
        'feratel': CalendarCalendarInnerChannelsAgodaToJSON(value.feratel),
        'goibibo': CalendarCalendarInnerChannelsAgodaToJSON(value.goibibo),
        'hometogo': CalendarCalendarInnerChannelsAgodaToJSON(value.hometogo),
        'hostelworld': CalendarCalendarInnerChannelsAgodaToJSON(value.hostelworld),
        'hotelbeds': CalendarCalendarInnerChannelsAgodaToJSON(value.hotelbeds),
        'hrs': CalendarCalendarInnerChannelsAgodaToJSON(value.hrs),
        'jomres': CalendarCalendarInnerChannelsAgodaToJSON(value.jomres),
        'marriott': CalendarCalendarInnerChannelsAgodaToJSON(value.marriott),
        'ostrovokru': CalendarCalendarInnerChannelsAgodaToJSON(value.ostrovokru),
        'ota': CalendarCalendarInnerChannelsAgodaToJSON(value.ota),
        'reserva': CalendarCalendarInnerChannelsAgodaToJSON(value.reserva),
        'tiket': CalendarCalendarInnerChannelsAgodaToJSON(value.tiket),
        'tomastravel': CalendarCalendarInnerChannelsAgodaToJSON(value.tomastravel),
        'traveloka': CalendarCalendarInnerChannelsAgodaToJSON(value.traveloka),
        'travia': CalendarCalendarInnerChannelsAgodaToJSON(value.travia),
        'traum': CalendarCalendarInnerChannelsAgodaToJSON(value.traum),
        'trip': CalendarCalendarInnerChannelsAgodaToJSON(value.trip),
        'tripadvisorrentals': CalendarCalendarInnerChannelsAgodaToJSON(value.tripadvisorrentals),
        'vacationstay': CalendarCalendarInnerChannelsAgodaToJSON(value.vacationstay),
        'vrbo': CalendarCalendarInnerChannelsAgodaToJSON(value.vrbo),
    };
}

