/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChannelsSettingsGet200ResponseAllOfDataInner } from './ChannelsSettingsGet200ResponseAllOfDataInner';
import {
    ChannelsSettingsGet200ResponseAllOfDataInnerFromJSON,
    ChannelsSettingsGet200ResponseAllOfDataInnerFromJSONTyped,
    ChannelsSettingsGet200ResponseAllOfDataInnerToJSON,
} from './ChannelsSettingsGet200ResponseAllOfDataInner';
import type { Pages } from './Pages';
import {
    PagesFromJSON,
    PagesFromJSONTyped,
    PagesToJSON,
} from './Pages';

/**
 * 
 * @export
 * @interface ChannelsSettingsGet200Response
 */
export interface ChannelsSettingsGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ChannelsSettingsGet200Response
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ChannelsSettingsGet200Response
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof ChannelsSettingsGet200Response
     */
    count?: number;
    /**
     * 
     * @type {Pages}
     * @memberof ChannelsSettingsGet200Response
     */
    pages?: Pages;
    /**
     * 
     * @type {Array<ChannelsSettingsGet200ResponseAllOfDataInner>}
     * @memberof ChannelsSettingsGet200Response
     */
    data?: Array<ChannelsSettingsGet200ResponseAllOfDataInner>;
}

/**
 * Check if a given object implements the ChannelsSettingsGet200Response interface.
 */
export function instanceOfChannelsSettingsGet200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "success" in value;

    return isInstance;
}

export function ChannelsSettingsGet200ResponseFromJSON(json: any): ChannelsSettingsGet200Response {
    return ChannelsSettingsGet200ResponseFromJSONTyped(json, false);
}

export function ChannelsSettingsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelsSettingsGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'count': !exists(json, 'count') ? undefined : json['count'],
        'pages': !exists(json, 'pages') ? undefined : PagesFromJSON(json['pages']),
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(ChannelsSettingsGet200ResponseAllOfDataInnerFromJSON)),
    };
}

export function ChannelsSettingsGet200ResponseToJSON(value?: ChannelsSettingsGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'type': value.type,
        'count': value.count,
        'pages': PagesToJSON(value.pages),
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(ChannelsSettingsGet200ResponseAllOfDataInnerToJSON)),
    };
}

