/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Pages } from './Pages';
import {
    PagesFromJSON,
    PagesFromJSONTyped,
    PagesToJSON,
} from './Pages';
import type { StripePaymentMethod } from './StripePaymentMethod';
import {
    StripePaymentMethodFromJSON,
    StripePaymentMethodFromJSONTyped,
    StripePaymentMethodToJSON,
} from './StripePaymentMethod';

/**
 * 
 * @export
 * @interface ChannelsStripePaymentMethodsGet200Response
 */
export interface ChannelsStripePaymentMethodsGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ChannelsStripePaymentMethodsGet200Response
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ChannelsStripePaymentMethodsGet200Response
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof ChannelsStripePaymentMethodsGet200Response
     */
    count?: number;
    /**
     * 
     * @type {Pages}
     * @memberof ChannelsStripePaymentMethodsGet200Response
     */
    pages?: Pages;
    /**
     * 
     * @type {Array<StripePaymentMethod>}
     * @memberof ChannelsStripePaymentMethodsGet200Response
     */
    data?: Array<StripePaymentMethod>;
}

/**
 * Check if a given object implements the ChannelsStripePaymentMethodsGet200Response interface.
 */
export function instanceOfChannelsStripePaymentMethodsGet200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "success" in value;

    return isInstance;
}

export function ChannelsStripePaymentMethodsGet200ResponseFromJSON(json: any): ChannelsStripePaymentMethodsGet200Response {
    return ChannelsStripePaymentMethodsGet200ResponseFromJSONTyped(json, false);
}

export function ChannelsStripePaymentMethodsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelsStripePaymentMethodsGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'count': !exists(json, 'count') ? undefined : json['count'],
        'pages': !exists(json, 'pages') ? undefined : PagesFromJSON(json['pages']),
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(StripePaymentMethodFromJSON)),
    };
}

export function ChannelsStripePaymentMethodsGet200ResponseToJSON(value?: ChannelsStripePaymentMethodsGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'type': value.type,
        'count': value.count,
        'pages': PagesToJSON(value.pages),
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(StripePaymentMethodToJSON)),
    };
}

