/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AirbnbSettingsPost } from './AirbnbSettingsPost';
import {
    AirbnbSettingsPostFromJSON,
    AirbnbSettingsPostFromJSONTyped,
    AirbnbSettingsPostToJSON,
} from './AirbnbSettingsPost';
import type { ICalExportSettingsPost } from './ICalExportSettingsPost';
import {
    ICalExportSettingsPostFromJSON,
    ICalExportSettingsPostFromJSONTyped,
    ICalExportSettingsPostToJSON,
} from './ICalExportSettingsPost';
import type { ICalImportSettingsPost } from './ICalImportSettingsPost';
import {
    ICalImportSettingsPostFromJSON,
    ICalImportSettingsPostFromJSONTyped,
    ICalImportSettingsPostToJSON,
} from './ICalImportSettingsPost';
import type { ICalImportSettingsPostAllOfProperties } from './ICalImportSettingsPostAllOfProperties';
import {
    ICalImportSettingsPostAllOfPropertiesFromJSON,
    ICalImportSettingsPostAllOfPropertiesFromJSONTyped,
    ICalImportSettingsPostAllOfPropertiesToJSON,
} from './ICalImportSettingsPostAllOfProperties';

/**
 * 
 * @export
 * @interface ChannelsSettingsPostRequestInner
 */
export interface ChannelsSettingsPostRequestInner {
    /**
     * 
     * @type {string}
     * @memberof ChannelsSettingsPostRequestInner
     */
    channel?: string;
    /**
     * 
     * @type {Array<ICalImportSettingsPostAllOfProperties>}
     * @memberof ChannelsSettingsPostRequestInner
     */
    properties?: Array<ICalImportSettingsPostAllOfProperties>;
}

/**
 * Check if a given object implements the ChannelsSettingsPostRequestInner interface.
 */
export function instanceOfChannelsSettingsPostRequestInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChannelsSettingsPostRequestInnerFromJSON(json: any): ChannelsSettingsPostRequestInner {
    return ChannelsSettingsPostRequestInnerFromJSONTyped(json, false);
}

export function ChannelsSettingsPostRequestInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelsSettingsPostRequestInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channel': !exists(json, 'channel') ? undefined : json['channel'],
        'properties': !exists(json, 'properties') ? undefined : ((json['properties'] as Array<any>).map(ICalImportSettingsPostAllOfPropertiesFromJSON)),
    };
}

export function ChannelsSettingsPostRequestInnerToJSON(value?: ChannelsSettingsPostRequestInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel': value.channel,
        'properties': value.properties === undefined ? undefined : ((value.properties as Array<any>).map(ICalImportSettingsPostAllOfPropertiesToJSON)),
    };
}

