/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChannelSettingsTemplatePropertiesRoomTypesInner } from './ChannelSettingsTemplatePropertiesRoomTypesInner';
import {
    ChannelSettingsTemplatePropertiesRoomTypesInnerFromJSON,
    ChannelSettingsTemplatePropertiesRoomTypesInnerFromJSONTyped,
    ChannelSettingsTemplatePropertiesRoomTypesInnerToJSON,
} from './ChannelSettingsTemplatePropertiesRoomTypesInner';

/**
 * 
 * @export
 * @interface ChannelSettingsTemplateProperties
 */
export interface ChannelSettingsTemplateProperties {
    /**
     * 
     * @type {number}
     * @memberof ChannelSettingsTemplateProperties
     */
    id?: number;
    /**
     * 
     * @type {Array<ChannelSettingsTemplatePropertiesRoomTypesInner>}
     * @memberof ChannelSettingsTemplateProperties
     */
    roomTypes?: Array<ChannelSettingsTemplatePropertiesRoomTypesInner>;
}

/**
 * Check if a given object implements the ChannelSettingsTemplateProperties interface.
 */
export function instanceOfChannelSettingsTemplateProperties(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChannelSettingsTemplatePropertiesFromJSON(json: any): ChannelSettingsTemplateProperties {
    return ChannelSettingsTemplatePropertiesFromJSONTyped(json, false);
}

export function ChannelSettingsTemplatePropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelSettingsTemplateProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'roomTypes': !exists(json, 'roomTypes') ? undefined : ((json['roomTypes'] as Array<any>).map(ChannelSettingsTemplatePropertiesRoomTypesInnerFromJSON)),
    };
}

export function ChannelSettingsTemplatePropertiesToJSON(value?: ChannelSettingsTemplateProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'roomTypes': value.roomTypes === undefined ? undefined : ((value.roomTypes as Array<any>).map(ChannelSettingsTemplatePropertiesRoomTypesInnerToJSON)),
    };
}

