/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ICalImportSettingsGetPropertiesInnerRoomTypesInner
 */
export interface ICalImportSettingsGetPropertiesInnerRoomTypesInner {
    /**
     * 
     * @type {number}
     * @memberof ICalImportSettingsGetPropertiesInnerRoomTypesInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ICalImportSettingsGetPropertiesInnerRoomTypesInner
     */
    iCalUri1?: string;
    /**
     * 
     * @type {string}
     * @memberof ICalImportSettingsGetPropertiesInnerRoomTypesInner
     */
    iCalUri2?: string;
    /**
     * 
     * @type {string}
     * @memberof ICalImportSettingsGetPropertiesInnerRoomTypesInner
     */
    iCalUri3?: string;
    /**
     * 
     * @type {string}
     * @memberof ICalImportSettingsGetPropertiesInnerRoomTypesInner
     */
    ignoreContaining1?: string;
    /**
     * 
     * @type {string}
     * @memberof ICalImportSettingsGetPropertiesInnerRoomTypesInner
     */
    ignoreContaining2?: string;
    /**
     * 
     * @type {string}
     * @memberof ICalImportSettingsGetPropertiesInnerRoomTypesInner
     */
    ignoreContaining3?: string;
    /**
     * 
     * @type {string}
     * @memberof ICalImportSettingsGetPropertiesInnerRoomTypesInner
     */
    import1?: ICalImportSettingsGetPropertiesInnerRoomTypesInnerImport1Enum;
    /**
     * 
     * @type {string}
     * @memberof ICalImportSettingsGetPropertiesInnerRoomTypesInner
     */
    import2?: ICalImportSettingsGetPropertiesInnerRoomTypesInnerImport2Enum;
    /**
     * 
     * @type {string}
     * @memberof ICalImportSettingsGetPropertiesInnerRoomTypesInner
     */
    import3?: ICalImportSettingsGetPropertiesInnerRoomTypesInnerImport3Enum;
}


/**
 * @export
 */
export const ICalImportSettingsGetPropertiesInnerRoomTypesInnerImport1Enum = {
    Disable: 'disable',
    EndDateCheckout: 'endDateCheckout',
    EndDateCheckoutIgnoreDuplicate: 'endDateCheckoutIgnoreDuplicate',
    EndDateCheckoutIgnoreIfUnavailable: 'endDateCheckoutIgnoreIfUnavailable',
    EndDateLastNight: 'endDateLastNight',
    EndDateLastNightIgnoreDuplicate: 'endDateLastNightIgnoreDuplicate',
    EndDateLastNightIgnoreIfUnavailable: 'endDateLastNightIgnoreIfUnavailable',
    EndDateDayAfterCheckOut: 'endDateDayAfterCheckOut',
    EndDateDayAfterCheckOutIgnoreDuplicate: 'endDateDayAfterCheckOutIgnoreDuplicate',
    EndDateDayAfterCheckoutIgnoreIfUnavailable: 'endDateDayAfterCheckoutIgnoreIfUnavailable'
} as const;
export type ICalImportSettingsGetPropertiesInnerRoomTypesInnerImport1Enum = typeof ICalImportSettingsGetPropertiesInnerRoomTypesInnerImport1Enum[keyof typeof ICalImportSettingsGetPropertiesInnerRoomTypesInnerImport1Enum];

/**
 * @export
 */
export const ICalImportSettingsGetPropertiesInnerRoomTypesInnerImport2Enum = {
    Disable: 'disable',
    EndDateCheckout: 'endDateCheckout',
    EndDateCheckoutIgnoreDuplicate: 'endDateCheckoutIgnoreDuplicate',
    EndDateCheckoutIgnoreIfUnavailable: 'endDateCheckoutIgnoreIfUnavailable',
    EndDateLastNight: 'endDateLastNight',
    EndDateLastNightIgnoreDuplicate: 'endDateLastNightIgnoreDuplicate',
    EndDateLastNightIgnoreIfUnavailable: 'endDateLastNightIgnoreIfUnavailable',
    EndDateDayAfterCheckOut: 'endDateDayAfterCheckOut',
    EndDateDayAfterCheckOutIgnoreDuplicate: 'endDateDayAfterCheckOutIgnoreDuplicate',
    EndDateDayAfterCheckoutIgnoreIfUnavailable: 'endDateDayAfterCheckoutIgnoreIfUnavailable'
} as const;
export type ICalImportSettingsGetPropertiesInnerRoomTypesInnerImport2Enum = typeof ICalImportSettingsGetPropertiesInnerRoomTypesInnerImport2Enum[keyof typeof ICalImportSettingsGetPropertiesInnerRoomTypesInnerImport2Enum];

/**
 * @export
 */
export const ICalImportSettingsGetPropertiesInnerRoomTypesInnerImport3Enum = {
    Disable: 'disable',
    EndDateCheckout: 'endDateCheckout',
    EndDateCheckoutIgnoreDuplicate: 'endDateCheckoutIgnoreDuplicate',
    EndDateCheckoutIgnoreIfUnavailable: 'endDateCheckoutIgnoreIfUnavailable',
    EndDateLastNight: 'endDateLastNight',
    EndDateLastNightIgnoreDuplicate: 'endDateLastNightIgnoreDuplicate',
    EndDateLastNightIgnoreIfUnavailable: 'endDateLastNightIgnoreIfUnavailable',
    EndDateDayAfterCheckOut: 'endDateDayAfterCheckOut',
    EndDateDayAfterCheckOutIgnoreDuplicate: 'endDateDayAfterCheckOutIgnoreDuplicate',
    EndDateDayAfterCheckoutIgnoreIfUnavailable: 'endDateDayAfterCheckoutIgnoreIfUnavailable'
} as const;
export type ICalImportSettingsGetPropertiesInnerRoomTypesInnerImport3Enum = typeof ICalImportSettingsGetPropertiesInnerRoomTypesInnerImport3Enum[keyof typeof ICalImportSettingsGetPropertiesInnerRoomTypesInnerImport3Enum];


/**
 * Check if a given object implements the ICalImportSettingsGetPropertiesInnerRoomTypesInner interface.
 */
export function instanceOfICalImportSettingsGetPropertiesInnerRoomTypesInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ICalImportSettingsGetPropertiesInnerRoomTypesInnerFromJSON(json: any): ICalImportSettingsGetPropertiesInnerRoomTypesInner {
    return ICalImportSettingsGetPropertiesInnerRoomTypesInnerFromJSONTyped(json, false);
}

export function ICalImportSettingsGetPropertiesInnerRoomTypesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ICalImportSettingsGetPropertiesInnerRoomTypesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'iCalUri1': !exists(json, 'iCalUri1') ? undefined : json['iCalUri1'],
        'iCalUri2': !exists(json, 'iCalUri2') ? undefined : json['iCalUri2'],
        'iCalUri3': !exists(json, 'iCalUri3') ? undefined : json['iCalUri3'],
        'ignoreContaining1': !exists(json, 'ignoreContaining1') ? undefined : json['ignoreContaining1'],
        'ignoreContaining2': !exists(json, 'ignoreContaining2') ? undefined : json['ignoreContaining2'],
        'ignoreContaining3': !exists(json, 'ignoreContaining3') ? undefined : json['ignoreContaining3'],
        'import1': !exists(json, 'import1') ? undefined : json['import1'],
        'import2': !exists(json, 'import2') ? undefined : json['import2'],
        'import3': !exists(json, 'import3') ? undefined : json['import3'],
    };
}

export function ICalImportSettingsGetPropertiesInnerRoomTypesInnerToJSON(value?: ICalImportSettingsGetPropertiesInnerRoomTypesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'iCalUri1': value.iCalUri1,
        'iCalUri2': value.iCalUri2,
        'iCalUri3': value.iCalUri3,
        'ignoreContaining1': value.ignoreContaining1,
        'ignoreContaining2': value.ignoreContaining2,
        'ignoreContaining3': value.ignoreContaining3,
        'import1': value.import1,
        'import2': value.import2,
        'import3': value.import3,
    };
}

