/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ICalExportSettingsPostPropertiesInner } from './ICalExportSettingsPostPropertiesInner';
import {
    ICalExportSettingsPostPropertiesInnerFromJSON,
    ICalExportSettingsPostPropertiesInnerFromJSONTyped,
    ICalExportSettingsPostPropertiesInnerToJSON,
} from './ICalExportSettingsPostPropertiesInner';

/**
 * 
 * @export
 * @interface ICalExportSettingsPost
 */
export interface ICalExportSettingsPost {
    /**
     * 
     * @type {string}
     * @memberof ICalExportSettingsPost
     */
    channel?: string;
    /**
     * 
     * @type {Array<ICalExportSettingsPostPropertiesInner>}
     * @memberof ICalExportSettingsPost
     */
    properties?: Array<ICalExportSettingsPostPropertiesInner>;
}

/**
 * Check if a given object implements the ICalExportSettingsPost interface.
 */
export function instanceOfICalExportSettingsPost(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ICalExportSettingsPostFromJSON(json: any): ICalExportSettingsPost {
    return ICalExportSettingsPostFromJSONTyped(json, false);
}

export function ICalExportSettingsPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): ICalExportSettingsPost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channel': !exists(json, 'channel') ? undefined : json['channel'],
        'properties': !exists(json, 'properties') ? undefined : ((json['properties'] as Array<any>).map(ICalExportSettingsPostPropertiesInnerFromJSON)),
    };
}

export function ICalExportSettingsPostToJSON(value?: ICalExportSettingsPost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel': value.channel,
        'properties': value.properties === undefined ? undefined : ((value.properties as Array<any>).map(ICalExportSettingsPostPropertiesInnerToJSON)),
    };
}

