/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ICalImportTools
 */
export interface ICalImportTools {
    /**
     * 
     * @type {boolean}
     * @memberof ICalImportTools
     */
    deleteBookingTool1?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ICalImportTools
     */
    deleteBookingTool2?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ICalImportTools
     */
    deleteBookingTool3?: boolean;
}

/**
 * Check if a given object implements the ICalImportTools interface.
 */
export function instanceOfICalImportTools(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ICalImportToolsFromJSON(json: any): ICalImportTools {
    return ICalImportToolsFromJSONTyped(json, false);
}

export function ICalImportToolsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ICalImportTools {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deleteBookingTool1': !exists(json, 'deleteBookingTool1') ? undefined : json['deleteBookingTool1'],
        'deleteBookingTool2': !exists(json, 'deleteBookingTool2') ? undefined : json['deleteBookingTool2'],
        'deleteBookingTool3': !exists(json, 'deleteBookingTool3') ? undefined : json['deleteBookingTool3'],
    };
}

export function ICalImportToolsToJSON(value?: ICalImportTools | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deleteBookingTool1': value.deleteBookingTool1,
        'deleteBookingTool2': value.deleteBookingTool2,
        'deleteBookingTool3': value.deleteBookingTool3,
    };
}

