/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ICalImportSettingsGetPropertiesInnerRoomTypesInner } from './ICalImportSettingsGetPropertiesInnerRoomTypesInner';
import {
    ICalImportSettingsGetPropertiesInnerRoomTypesInnerFromJSON,
    ICalImportSettingsGetPropertiesInnerRoomTypesInnerFromJSONTyped,
    ICalImportSettingsGetPropertiesInnerRoomTypesInnerToJSON,
} from './ICalImportSettingsGetPropertiesInnerRoomTypesInner';

/**
 * 
 * @export
 * @interface ICalImportSettingsGetPropertiesInner
 */
export interface ICalImportSettingsGetPropertiesInner {
    /**
     * 
     * @type {number}
     * @memberof ICalImportSettingsGetPropertiesInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ICalImportSettingsGetPropertiesInner
     */
    modificationNotification?: ICalImportSettingsGetPropertiesInnerModificationNotificationEnum;
    /**
     * 
     * @type {Array<ICalImportSettingsGetPropertiesInnerRoomTypesInner>}
     * @memberof ICalImportSettingsGetPropertiesInner
     */
    roomTypes?: Array<ICalImportSettingsGetPropertiesInnerRoomTypesInner>;
}


/**
 * @export
 */
export const ICalImportSettingsGetPropertiesInnerModificationNotificationEnum = {
    ModificationAllowedBookingNotificationOnly: 'modificationAllowedBookingNotificationOnly',
    ModificationAllowedBookingCancelNotification: 'modificationAllowedBookingCancelNotification',
    ModificationAllowedNoEmailNotification: 'modificationAllowedNoEmailNotification',
    ModificationProhibitedBookingNotificationOnly: 'modificationProhibitedBookingNotificationOnly',
    ModificationProhibitedNoEmailNotification: 'modificationProhibitedNoEmailNotification'
} as const;
export type ICalImportSettingsGetPropertiesInnerModificationNotificationEnum = typeof ICalImportSettingsGetPropertiesInnerModificationNotificationEnum[keyof typeof ICalImportSettingsGetPropertiesInnerModificationNotificationEnum];


/**
 * Check if a given object implements the ICalImportSettingsGetPropertiesInner interface.
 */
export function instanceOfICalImportSettingsGetPropertiesInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ICalImportSettingsGetPropertiesInnerFromJSON(json: any): ICalImportSettingsGetPropertiesInner {
    return ICalImportSettingsGetPropertiesInnerFromJSONTyped(json, false);
}

export function ICalImportSettingsGetPropertiesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ICalImportSettingsGetPropertiesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'modificationNotification': !exists(json, 'modificationNotification') ? undefined : json['modificationNotification'],
        'roomTypes': !exists(json, 'roomTypes') ? undefined : ((json['roomTypes'] as Array<any>).map(ICalImportSettingsGetPropertiesInnerRoomTypesInnerFromJSON)),
    };
}

export function ICalImportSettingsGetPropertiesInnerToJSON(value?: ICalImportSettingsGetPropertiesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'modificationNotification': value.modificationNotification,
        'roomTypes': value.roomTypes === undefined ? undefined : ((value.roomTypes as Array<any>).map(ICalImportSettingsGetPropertiesInnerRoomTypesInnerToJSON)),
    };
}

