/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MultiplePostResponseErrorsInner
 */
export interface MultiplePostResponseErrorsInner {
    /**
     * 
     * @type {string}
     * @memberof MultiplePostResponseErrorsInner
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof MultiplePostResponseErrorsInner
     */
    field?: string;
    /**
     * 
     * @type {string}
     * @memberof MultiplePostResponseErrorsInner
     */
    message?: string;
}

/**
 * Check if a given object implements the MultiplePostResponseErrorsInner interface.
 */
export function instanceOfMultiplePostResponseErrorsInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MultiplePostResponseErrorsInnerFromJSON(json: any): MultiplePostResponseErrorsInner {
    return MultiplePostResponseErrorsInnerFromJSONTyped(json, false);
}

export function MultiplePostResponseErrorsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiplePostResponseErrorsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': !exists(json, 'action') ? undefined : json['action'],
        'field': !exists(json, 'field') ? undefined : json['field'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function MultiplePostResponseErrorsInnerToJSON(value?: MultiplePostResponseErrorsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'field': value.field,
        'message': value.message,
    };
}

