/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewBookingInfoItemsInner
 */
export interface NewBookingInfoItemsInner {
    /**
     * 
     * @type {string}
     * @memberof NewBookingInfoItemsInner
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof NewBookingInfoItemsInner
     */
    text?: string;
    /**
     * 
     * @type {number}
     * @memberof NewBookingInfoItemsInner
     */
    bookingId?: number;
}

/**
 * Check if a given object implements the NewBookingInfoItemsInner interface.
 */
export function instanceOfNewBookingInfoItemsInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NewBookingInfoItemsInnerFromJSON(json: any): NewBookingInfoItemsInner {
    return NewBookingInfoItemsInnerFromJSONTyped(json, false);
}

export function NewBookingInfoItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewBookingInfoItemsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'text': !exists(json, 'text') ? undefined : json['text'],
        'bookingId': !exists(json, 'bookingId') ? undefined : json['bookingId'],
    };
}

export function NewBookingInfoItemsInnerToJSON(value?: NewBookingInfoItemsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'text': value.text,
        'bookingId': value.bookingId,
    };
}

