/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NukiSettingsGetPropertiesRoomTypesInnerLockSerialNumbersInner
 */
export interface NukiSettingsGetPropertiesRoomTypesInnerLockSerialNumbersInner {
    /**
     * 
     * @type {number}
     * @memberof NukiSettingsGetPropertiesRoomTypesInnerLockSerialNumbersInner
     */
    number?: number;
    /**
     * 
     * @type {number}
     * @memberof NukiSettingsGetPropertiesRoomTypesInnerLockSerialNumbersInner
     */
    serial?: number;
}

/**
 * Check if a given object implements the NukiSettingsGetPropertiesRoomTypesInnerLockSerialNumbersInner interface.
 */
export function instanceOfNukiSettingsGetPropertiesRoomTypesInnerLockSerialNumbersInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NukiSettingsGetPropertiesRoomTypesInnerLockSerialNumbersInnerFromJSON(json: any): NukiSettingsGetPropertiesRoomTypesInnerLockSerialNumbersInner {
    return NukiSettingsGetPropertiesRoomTypesInnerLockSerialNumbersInnerFromJSONTyped(json, false);
}

export function NukiSettingsGetPropertiesRoomTypesInnerLockSerialNumbersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NukiSettingsGetPropertiesRoomTypesInnerLockSerialNumbersInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': !exists(json, 'number') ? undefined : json['number'],
        'serial': !exists(json, 'serial') ? undefined : json['serial'],
    };
}

export function NukiSettingsGetPropertiesRoomTypesInnerLockSerialNumbersInnerToJSON(value?: NukiSettingsGetPropertiesRoomTypesInnerLockSerialNumbersInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
        'serial': value.serial,
    };
}

