/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Used to link this price to another price
 * @export
 * @interface PriceRulesPriceLinking
 */
export interface PriceRulesPriceLinking {
    /**
     * 
     * @type {number}
     * @memberof PriceRulesPriceLinking
     */
    roomId?: number | null;
    /**
     * Set to null to disable the link
     * @type {number}
     * @memberof PriceRulesPriceLinking
     */
    priceId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PriceRulesPriceLinking
     */
    offsetMultiplier?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PriceRulesPriceLinking
     */
    offsetAmount?: number | null;
}

/**
 * Check if a given object implements the PriceRulesPriceLinking interface.
 */
export function instanceOfPriceRulesPriceLinking(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PriceRulesPriceLinkingFromJSON(json: any): PriceRulesPriceLinking {
    return PriceRulesPriceLinkingFromJSONTyped(json, false);
}

export function PriceRulesPriceLinkingFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceRulesPriceLinking {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roomId': !exists(json, 'roomId') ? undefined : json['roomId'],
        'priceId': !exists(json, 'priceId') ? undefined : json['priceId'],
        'offsetMultiplier': !exists(json, 'offsetMultiplier') ? undefined : json['offsetMultiplier'],
        'offsetAmount': !exists(json, 'offsetAmount') ? undefined : json['offsetAmount'],
    };
}

export function PriceRulesPriceLinkingToJSON(value?: PriceRulesPriceLinking | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'roomId': value.roomId,
        'priceId': value.priceId,
        'offsetMultiplier': value.offsetMultiplier,
        'offsetAmount': value.offsetAmount,
    };
}

