/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceRulesChannelsAgoda
 */
export interface PriceRulesChannelsAgoda {
    /**
     * 
     * @type {boolean}
     * @memberof PriceRulesChannelsAgoda
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PriceRulesChannelsAgoda
     */
    rateCode?: string;
}

/**
 * Check if a given object implements the PriceRulesChannelsAgoda interface.
 */
export function instanceOfPriceRulesChannelsAgoda(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PriceRulesChannelsAgodaFromJSON(json: any): PriceRulesChannelsAgoda {
    return PriceRulesChannelsAgodaFromJSONTyped(json, false);
}

export function PriceRulesChannelsAgodaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceRulesChannelsAgoda {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'rateCode': !exists(json, 'rateCode') ? undefined : json['rateCode'],
    };
}

export function PriceRulesChannelsAgodaToJSON(value?: PriceRulesChannelsAgoda | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
        'rateCode': value.rateCode,
    };
}

