/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PropertyPaymentCollectionDepositPayment1VariableAmount } from './PropertyPaymentCollectionDepositPayment1VariableAmount';
import {
    PropertyPaymentCollectionDepositPayment1VariableAmountFromJSON,
    PropertyPaymentCollectionDepositPayment1VariableAmountFromJSONTyped,
    PropertyPaymentCollectionDepositPayment1VariableAmountToJSON,
} from './PropertyPaymentCollectionDepositPayment1VariableAmount';

/**
 * 
 * @export
 * @interface PropertyPaymentCollectionDepositPayment1
 */
export interface PropertyPaymentCollectionDepositPayment1 {
    /**
     * 
     * @type {number}
     * @memberof PropertyPaymentCollectionDepositPayment1
     */
    fixedAmount?: number;
    /**
     * 
     * @type {PropertyPaymentCollectionDepositPayment1VariableAmount}
     * @memberof PropertyPaymentCollectionDepositPayment1
     */
    variableAmount?: PropertyPaymentCollectionDepositPayment1VariableAmount;
}

/**
 * Check if a given object implements the PropertyPaymentCollectionDepositPayment1 interface.
 */
export function instanceOfPropertyPaymentCollectionDepositPayment1(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PropertyPaymentCollectionDepositPayment1FromJSON(json: any): PropertyPaymentCollectionDepositPayment1 {
    return PropertyPaymentCollectionDepositPayment1FromJSONTyped(json, false);
}

export function PropertyPaymentCollectionDepositPayment1FromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyPaymentCollectionDepositPayment1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fixedAmount': !exists(json, 'fixedAmount') ? undefined : json['fixedAmount'],
        'variableAmount': !exists(json, 'variableAmount') ? undefined : PropertyPaymentCollectionDepositPayment1VariableAmountFromJSON(json['variableAmount']),
    };
}

export function PropertyPaymentCollectionDepositPayment1ToJSON(value?: PropertyPaymentCollectionDepositPayment1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fixedAmount': value.fixedAmount,
        'variableAmount': PropertyPaymentCollectionDepositPayment1VariableAmountToJSON(value.variableAmount),
    };
}

