/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertyDiscountVouchersInner
 */
export interface PropertyDiscountVouchersInner {
    /**
     * 
     * @type {number}
     * @memberof PropertyDiscountVouchersInner
     */
    number?: number;
    /**
     * 
     * @type {string}
     * @memberof PropertyDiscountVouchersInner
     */
    phrase?: string;
    /**
     * 
     * @type {number}
     * @memberof PropertyDiscountVouchersInner
     */
    discount?: number;
    /**
     * 
     * @type {string}
     * @memberof PropertyDiscountVouchersInner
     */
    type?: PropertyDiscountVouchersInnerTypeEnum;
}


/**
 * @export
 */
export const PropertyDiscountVouchersInnerTypeEnum = {
    NotUsed: 'notUsed',
    Percentage: 'percentage',
    RoomOnlyPercentage: 'roomOnlyPercentage',
    ExtrasOnlyPercentage: 'extrasOnlyPercentage',
    FixedAmount: 'fixedAmount',
    FixedAmountPerNight: 'fixedAmountPerNight',
    Compulsory: 'compulsory'
} as const;
export type PropertyDiscountVouchersInnerTypeEnum = typeof PropertyDiscountVouchersInnerTypeEnum[keyof typeof PropertyDiscountVouchersInnerTypeEnum];


/**
 * Check if a given object implements the PropertyDiscountVouchersInner interface.
 */
export function instanceOfPropertyDiscountVouchersInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PropertyDiscountVouchersInnerFromJSON(json: any): PropertyDiscountVouchersInner {
    return PropertyDiscountVouchersInnerFromJSONTyped(json, false);
}

export function PropertyDiscountVouchersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyDiscountVouchersInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': !exists(json, 'number') ? undefined : json['number'],
        'phrase': !exists(json, 'phrase') ? undefined : json['phrase'],
        'discount': !exists(json, 'discount') ? undefined : json['discount'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function PropertyDiscountVouchersInnerToJSON(value?: PropertyDiscountVouchersInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
        'phrase': value.phrase,
        'discount': value.discount,
        'type': value.type,
    };
}

