/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PropertyBookingQuestionsCustomQuestion1 } from './PropertyBookingQuestionsCustomQuestion1';
import {
    PropertyBookingQuestionsCustomQuestion1FromJSON,
    PropertyBookingQuestionsCustomQuestion1FromJSONTyped,
    PropertyBookingQuestionsCustomQuestion1ToJSON,
} from './PropertyBookingQuestionsCustomQuestion1';
import type { PropertyBookingQuestionsGuestTitle } from './PropertyBookingQuestionsGuestTitle';
import {
    PropertyBookingQuestionsGuestTitleFromJSON,
    PropertyBookingQuestionsGuestTitleFromJSONTyped,
    PropertyBookingQuestionsGuestTitleToJSON,
} from './PropertyBookingQuestionsGuestTitle';

/**
 * 
 * @export
 * @interface PropertyBookingQuestions
 */
export interface PropertyBookingQuestions {
    /**
     * 
     * @type {PropertyBookingQuestionsGuestTitle}
     * @memberof PropertyBookingQuestions
     */
    guestTitle?: PropertyBookingQuestionsGuestTitle;
    /**
     * 
     * @type {PropertyBookingQuestionsGuestTitle}
     * @memberof PropertyBookingQuestions
     */
    guestFirstName?: PropertyBookingQuestionsGuestTitle;
    /**
     * 
     * @type {PropertyBookingQuestionsGuestTitle}
     * @memberof PropertyBookingQuestions
     */
    guestLastName?: PropertyBookingQuestionsGuestTitle;
    /**
     * 
     * @type {PropertyBookingQuestionsGuestTitle}
     * @memberof PropertyBookingQuestions
     */
    guestEmail?: PropertyBookingQuestionsGuestTitle;
    /**
     * 
     * @type {PropertyBookingQuestionsGuestTitle}
     * @memberof PropertyBookingQuestions
     */
    guestPhone?: PropertyBookingQuestionsGuestTitle;
    /**
     * 
     * @type {PropertyBookingQuestionsGuestTitle}
     * @memberof PropertyBookingQuestions
     */
    guestMobile?: PropertyBookingQuestionsGuestTitle;
    /**
     * 
     * @type {PropertyBookingQuestionsGuestTitle}
     * @memberof PropertyBookingQuestions
     */
    guestFax?: PropertyBookingQuestionsGuestTitle;
    /**
     * 
     * @type {PropertyBookingQuestionsGuestTitle}
     * @memberof PropertyBookingQuestions
     */
    guestCompany?: PropertyBookingQuestionsGuestTitle;
    /**
     * 
     * @type {PropertyBookingQuestionsGuestTitle}
     * @memberof PropertyBookingQuestions
     */
    guestAddress?: PropertyBookingQuestionsGuestTitle;
    /**
     * 
     * @type {PropertyBookingQuestionsGuestTitle}
     * @memberof PropertyBookingQuestions
     */
    guestCity?: PropertyBookingQuestionsGuestTitle;
    /**
     * 
     * @type {PropertyBookingQuestionsGuestTitle}
     * @memberof PropertyBookingQuestions
     */
    guestState?: PropertyBookingQuestionsGuestTitle;
    /**
     * 
     * @type {PropertyBookingQuestionsGuestTitle}
     * @memberof PropertyBookingQuestions
     */
    guestPostcode?: PropertyBookingQuestionsGuestTitle;
    /**
     * 
     * @type {PropertyBookingQuestionsGuestTitle}
     * @memberof PropertyBookingQuestions
     */
    guestCountryText?: PropertyBookingQuestionsGuestTitle;
    /**
     * 
     * @type {PropertyBookingQuestionsGuestTitle}
     * @memberof PropertyBookingQuestions
     */
    guestCountrySelect?: PropertyBookingQuestionsGuestTitle;
    /**
     * 
     * @type {PropertyBookingQuestionsGuestTitle}
     * @memberof PropertyBookingQuestions
     */
    guestArrivalTime?: PropertyBookingQuestionsGuestTitle;
    /**
     * 
     * @type {PropertyBookingQuestionsGuestTitle}
     * @memberof PropertyBookingQuestions
     */
    guestComments?: PropertyBookingQuestionsGuestTitle;
    /**
     * 
     * @type {PropertyBookingQuestionsCustomQuestion1}
     * @memberof PropertyBookingQuestions
     */
    customQuestion1?: PropertyBookingQuestionsCustomQuestion1;
    /**
     * 
     * @type {PropertyBookingQuestionsCustomQuestion1}
     * @memberof PropertyBookingQuestions
     */
    customQuestion2?: PropertyBookingQuestionsCustomQuestion1;
    /**
     * 
     * @type {PropertyBookingQuestionsCustomQuestion1}
     * @memberof PropertyBookingQuestions
     */
    customQuestion3?: PropertyBookingQuestionsCustomQuestion1;
    /**
     * 
     * @type {PropertyBookingQuestionsCustomQuestion1}
     * @memberof PropertyBookingQuestions
     */
    customQuestion4?: PropertyBookingQuestionsCustomQuestion1;
    /**
     * 
     * @type {PropertyBookingQuestionsCustomQuestion1}
     * @memberof PropertyBookingQuestions
     */
    customQuestion5?: PropertyBookingQuestionsCustomQuestion1;
    /**
     * 
     * @type {PropertyBookingQuestionsCustomQuestion1}
     * @memberof PropertyBookingQuestions
     */
    customQuestion6?: PropertyBookingQuestionsCustomQuestion1;
    /**
     * 
     * @type {PropertyBookingQuestionsCustomQuestion1}
     * @memberof PropertyBookingQuestions
     */
    customQuestion7?: PropertyBookingQuestionsCustomQuestion1;
    /**
     * 
     * @type {PropertyBookingQuestionsCustomQuestion1}
     * @memberof PropertyBookingQuestions
     */
    customQuestion8?: PropertyBookingQuestionsCustomQuestion1;
    /**
     * 
     * @type {PropertyBookingQuestionsCustomQuestion1}
     * @memberof PropertyBookingQuestions
     */
    customQuestion9?: PropertyBookingQuestionsCustomQuestion1;
    /**
     * 
     * @type {PropertyBookingQuestionsCustomQuestion1}
     * @memberof PropertyBookingQuestions
     */
    customQuestion10?: PropertyBookingQuestionsCustomQuestion1;
}

/**
 * Check if a given object implements the PropertyBookingQuestions interface.
 */
export function instanceOfPropertyBookingQuestions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PropertyBookingQuestionsFromJSON(json: any): PropertyBookingQuestions {
    return PropertyBookingQuestionsFromJSONTyped(json, false);
}

export function PropertyBookingQuestionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyBookingQuestions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'guestTitle': !exists(json, 'guestTitle') ? undefined : PropertyBookingQuestionsGuestTitleFromJSON(json['guestTitle']),
        'guestFirstName': !exists(json, 'guestFirstName') ? undefined : PropertyBookingQuestionsGuestTitleFromJSON(json['guestFirstName']),
        'guestLastName': !exists(json, 'guestLastName') ? undefined : PropertyBookingQuestionsGuestTitleFromJSON(json['guestLastName']),
        'guestEmail': !exists(json, 'guestEmail') ? undefined : PropertyBookingQuestionsGuestTitleFromJSON(json['guestEmail']),
        'guestPhone': !exists(json, 'guestPhone') ? undefined : PropertyBookingQuestionsGuestTitleFromJSON(json['guestPhone']),
        'guestMobile': !exists(json, 'guestMobile') ? undefined : PropertyBookingQuestionsGuestTitleFromJSON(json['guestMobile']),
        'guestFax': !exists(json, 'guestFax') ? undefined : PropertyBookingQuestionsGuestTitleFromJSON(json['guestFax']),
        'guestCompany': !exists(json, 'guestCompany') ? undefined : PropertyBookingQuestionsGuestTitleFromJSON(json['guestCompany']),
        'guestAddress': !exists(json, 'guestAddress') ? undefined : PropertyBookingQuestionsGuestTitleFromJSON(json['guestAddress']),
        'guestCity': !exists(json, 'guestCity') ? undefined : PropertyBookingQuestionsGuestTitleFromJSON(json['guestCity']),
        'guestState': !exists(json, 'guestState') ? undefined : PropertyBookingQuestionsGuestTitleFromJSON(json['guestState']),
        'guestPostcode': !exists(json, 'guestPostcode') ? undefined : PropertyBookingQuestionsGuestTitleFromJSON(json['guestPostcode']),
        'guestCountryText': !exists(json, 'guestCountryText') ? undefined : PropertyBookingQuestionsGuestTitleFromJSON(json['guestCountryText']),
        'guestCountrySelect': !exists(json, 'guestCountrySelect') ? undefined : PropertyBookingQuestionsGuestTitleFromJSON(json['guestCountrySelect']),
        'guestArrivalTime': !exists(json, 'guestArrivalTime') ? undefined : PropertyBookingQuestionsGuestTitleFromJSON(json['guestArrivalTime']),
        'guestComments': !exists(json, 'guestComments') ? undefined : PropertyBookingQuestionsGuestTitleFromJSON(json['guestComments']),
        'customQuestion1': !exists(json, 'customQuestion1') ? undefined : PropertyBookingQuestionsCustomQuestion1FromJSON(json['customQuestion1']),
        'customQuestion2': !exists(json, 'customQuestion2') ? undefined : PropertyBookingQuestionsCustomQuestion1FromJSON(json['customQuestion2']),
        'customQuestion3': !exists(json, 'customQuestion3') ? undefined : PropertyBookingQuestionsCustomQuestion1FromJSON(json['customQuestion3']),
        'customQuestion4': !exists(json, 'customQuestion4') ? undefined : PropertyBookingQuestionsCustomQuestion1FromJSON(json['customQuestion4']),
        'customQuestion5': !exists(json, 'customQuestion5') ? undefined : PropertyBookingQuestionsCustomQuestion1FromJSON(json['customQuestion5']),
        'customQuestion6': !exists(json, 'customQuestion6') ? undefined : PropertyBookingQuestionsCustomQuestion1FromJSON(json['customQuestion6']),
        'customQuestion7': !exists(json, 'customQuestion7') ? undefined : PropertyBookingQuestionsCustomQuestion1FromJSON(json['customQuestion7']),
        'customQuestion8': !exists(json, 'customQuestion8') ? undefined : PropertyBookingQuestionsCustomQuestion1FromJSON(json['customQuestion8']),
        'customQuestion9': !exists(json, 'customQuestion9') ? undefined : PropertyBookingQuestionsCustomQuestion1FromJSON(json['customQuestion9']),
        'customQuestion10': !exists(json, 'customQuestion10') ? undefined : PropertyBookingQuestionsCustomQuestion1FromJSON(json['customQuestion10']),
    };
}

export function PropertyBookingQuestionsToJSON(value?: PropertyBookingQuestions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'guestTitle': PropertyBookingQuestionsGuestTitleToJSON(value.guestTitle),
        'guestFirstName': PropertyBookingQuestionsGuestTitleToJSON(value.guestFirstName),
        'guestLastName': PropertyBookingQuestionsGuestTitleToJSON(value.guestLastName),
        'guestEmail': PropertyBookingQuestionsGuestTitleToJSON(value.guestEmail),
        'guestPhone': PropertyBookingQuestionsGuestTitleToJSON(value.guestPhone),
        'guestMobile': PropertyBookingQuestionsGuestTitleToJSON(value.guestMobile),
        'guestFax': PropertyBookingQuestionsGuestTitleToJSON(value.guestFax),
        'guestCompany': PropertyBookingQuestionsGuestTitleToJSON(value.guestCompany),
        'guestAddress': PropertyBookingQuestionsGuestTitleToJSON(value.guestAddress),
        'guestCity': PropertyBookingQuestionsGuestTitleToJSON(value.guestCity),
        'guestState': PropertyBookingQuestionsGuestTitleToJSON(value.guestState),
        'guestPostcode': PropertyBookingQuestionsGuestTitleToJSON(value.guestPostcode),
        'guestCountryText': PropertyBookingQuestionsGuestTitleToJSON(value.guestCountryText),
        'guestCountrySelect': PropertyBookingQuestionsGuestTitleToJSON(value.guestCountrySelect),
        'guestArrivalTime': PropertyBookingQuestionsGuestTitleToJSON(value.guestArrivalTime),
        'guestComments': PropertyBookingQuestionsGuestTitleToJSON(value.guestComments),
        'customQuestion1': PropertyBookingQuestionsCustomQuestion1ToJSON(value.customQuestion1),
        'customQuestion2': PropertyBookingQuestionsCustomQuestion1ToJSON(value.customQuestion2),
        'customQuestion3': PropertyBookingQuestionsCustomQuestion1ToJSON(value.customQuestion3),
        'customQuestion4': PropertyBookingQuestionsCustomQuestion1ToJSON(value.customQuestion4),
        'customQuestion5': PropertyBookingQuestionsCustomQuestion1ToJSON(value.customQuestion5),
        'customQuestion6': PropertyBookingQuestionsCustomQuestion1ToJSON(value.customQuestion6),
        'customQuestion7': PropertyBookingQuestionsCustomQuestion1ToJSON(value.customQuestion7),
        'customQuestion8': PropertyBookingQuestionsCustomQuestion1ToJSON(value.customQuestion8),
        'customQuestion9': PropertyBookingQuestionsCustomQuestion1ToJSON(value.customQuestion9),
        'customQuestion10': PropertyBookingQuestionsCustomQuestion1ToJSON(value.customQuestion10),
    };
}

