/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertyPaymentCollectionDepositPayment1VariableAmount
 */
export interface PropertyPaymentCollectionDepositPayment1VariableAmount {
    /**
     * 
     * @type {string}
     * @memberof PropertyPaymentCollectionDepositPayment1VariableAmount
     */
    type?: PropertyPaymentCollectionDepositPayment1VariableAmountTypeEnum;
    /**
     * Used to specify the deposit percentage if type is set to percentage
     * @type {number}
     * @memberof PropertyPaymentCollectionDepositPayment1VariableAmount
     */
    percentageValue?: number | null;
}


/**
 * @export
 */
export const PropertyPaymentCollectionDepositPayment1VariableAmountTypeEnum = {
    Percentage: 'percentage',
    FirstNight: 'firstNight'
} as const;
export type PropertyPaymentCollectionDepositPayment1VariableAmountTypeEnum = typeof PropertyPaymentCollectionDepositPayment1VariableAmountTypeEnum[keyof typeof PropertyPaymentCollectionDepositPayment1VariableAmountTypeEnum];


/**
 * Check if a given object implements the PropertyPaymentCollectionDepositPayment1VariableAmount interface.
 */
export function instanceOfPropertyPaymentCollectionDepositPayment1VariableAmount(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PropertyPaymentCollectionDepositPayment1VariableAmountFromJSON(json: any): PropertyPaymentCollectionDepositPayment1VariableAmount {
    return PropertyPaymentCollectionDepositPayment1VariableAmountFromJSONTyped(json, false);
}

export function PropertyPaymentCollectionDepositPayment1VariableAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyPaymentCollectionDepositPayment1VariableAmount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'percentageValue': !exists(json, 'percentageValue') ? undefined : json['percentageValue'],
    };
}

export function PropertyPaymentCollectionDepositPayment1VariableAmountToJSON(value?: PropertyPaymentCollectionDepositPayment1VariableAmount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'percentageValue': value.percentageValue,
    };
}

