/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StripeCreateSessionLineItemsInnerPriceDataProductData
 */
export interface StripeCreateSessionLineItemsInnerPriceDataProductData {
    /**
     * 
     * @type {string}
     * @memberof StripeCreateSessionLineItemsInnerPriceDataProductData
     */
    name?: string;
}

/**
 * Check if a given object implements the StripeCreateSessionLineItemsInnerPriceDataProductData interface.
 */
export function instanceOfStripeCreateSessionLineItemsInnerPriceDataProductData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StripeCreateSessionLineItemsInnerPriceDataProductDataFromJSON(json: any): StripeCreateSessionLineItemsInnerPriceDataProductData {
    return StripeCreateSessionLineItemsInnerPriceDataProductDataFromJSONTyped(json, false);
}

export function StripeCreateSessionLineItemsInnerPriceDataProductDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripeCreateSessionLineItemsInnerPriceDataProductData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function StripeCreateSessionLineItemsInnerPriceDataProductDataToJSON(value?: StripeCreateSessionLineItemsInnerPriceDataProductData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

