/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StripePaymentMethodStripePaymentMethodBillingDetails } from './StripePaymentMethodStripePaymentMethodBillingDetails';
import {
    StripePaymentMethodStripePaymentMethodBillingDetailsFromJSON,
    StripePaymentMethodStripePaymentMethodBillingDetailsFromJSONTyped,
    StripePaymentMethodStripePaymentMethodBillingDetailsToJSON,
} from './StripePaymentMethodStripePaymentMethodBillingDetails';

/**
 * This object will contain other fields not specified here.
 * @export
 * @interface StripePaymentMethodStripePaymentMethod
 */
export interface StripePaymentMethodStripePaymentMethod {
    /**
     * 
     * @type {string}
     * @memberof StripePaymentMethodStripePaymentMethod
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof StripePaymentMethodStripePaymentMethod
     */
    object?: string;
    /**
     * 
     * @type {StripePaymentMethodStripePaymentMethodBillingDetails}
     * @memberof StripePaymentMethodStripePaymentMethod
     */
    billingDetails?: StripePaymentMethodStripePaymentMethodBillingDetails;
}

/**
 * Check if a given object implements the StripePaymentMethodStripePaymentMethod interface.
 */
export function instanceOfStripePaymentMethodStripePaymentMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StripePaymentMethodStripePaymentMethodFromJSON(json: any): StripePaymentMethodStripePaymentMethod {
    return StripePaymentMethodStripePaymentMethodFromJSONTyped(json, false);
}

export function StripePaymentMethodStripePaymentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripePaymentMethodStripePaymentMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'object': !exists(json, 'object') ? undefined : json['object'],
        'billingDetails': !exists(json, 'billing_details') ? undefined : StripePaymentMethodStripePaymentMethodBillingDetailsFromJSON(json['billing_details']),
    };
}

export function StripePaymentMethodStripePaymentMethodToJSON(value?: StripePaymentMethodStripePaymentMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'object': value.object,
        'billing_details': StripePaymentMethodStripePaymentMethodBillingDetailsToJSON(value.billingDetails),
    };
}

