/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuccessfulApiResponse
 */
export interface SuccessfulApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessfulApiResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof SuccessfulApiResponse
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof SuccessfulApiResponse
     */
    count?: number;
}

/**
 * Check if a given object implements the SuccessfulApiResponse interface.
 */
export function instanceOfSuccessfulApiResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "success" in value;

    return isInstance;
}

export function SuccessfulApiResponseFromJSON(json: any): SuccessfulApiResponse {
    return SuccessfulApiResponseFromJSONTyped(json, false);
}

export function SuccessfulApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessfulApiResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'count': !exists(json, 'count') ? undefined : json['count'],
    };
}

export function SuccessfulApiResponseToJSON(value?: SuccessfulApiResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'type': value.type,
        'count': value.count,
    };
}

