/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenDetailsDiagnostics
 */
export interface TokenDetailsDiagnostics {
    /**
     * 
     * @type {string}
     * @memberof TokenDetailsDiagnostics
     */
    requestIp?: string;
}

/**
 * Check if a given object implements the TokenDetailsDiagnostics interface.
 */
export function instanceOfTokenDetailsDiagnostics(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TokenDetailsDiagnosticsFromJSON(json: any): TokenDetailsDiagnostics {
    return TokenDetailsDiagnosticsFromJSONTyped(json, false);
}

export function TokenDetailsDiagnosticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenDetailsDiagnostics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'requestIp': !exists(json, 'requestIp') ? undefined : json['requestIp'],
    };
}

export function TokenDetailsDiagnosticsToJSON(value?: TokenDetailsDiagnostics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'requestIp': value.requestIp,
    };
}

