/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VrboPaymentSchedule } from './VrboPaymentSchedule';
import {
    VrboPaymentScheduleFromJSON,
    VrboPaymentScheduleFromJSONTyped,
    VrboPaymentScheduleToJSON,
} from './VrboPaymentSchedule';

/**
 * 
 * @export
 * @interface VrboSettingsPostPropertiesRoomTypesInnerPaymentSchedules
 */
export interface VrboSettingsPostPropertiesRoomTypesInnerPaymentSchedules {
    /**
     * 
     * @type {string}
     * @memberof VrboSettingsPostPropertiesRoomTypesInnerPaymentSchedules
     */
    name?: string;
    /**
     * 
     * @type {VrboPaymentSchedule}
     * @memberof VrboSettingsPostPropertiesRoomTypesInnerPaymentSchedules
     */
    payment1?: VrboPaymentSchedule;
    /**
     * 
     * @type {VrboPaymentSchedule}
     * @memberof VrboSettingsPostPropertiesRoomTypesInnerPaymentSchedules
     */
    payment2?: VrboPaymentSchedule;
    /**
     * 
     * @type {VrboPaymentSchedule}
     * @memberof VrboSettingsPostPropertiesRoomTypesInnerPaymentSchedules
     */
    payment3?: VrboPaymentSchedule;
    /**
     * 
     * @type {VrboPaymentSchedule}
     * @memberof VrboSettingsPostPropertiesRoomTypesInnerPaymentSchedules
     */
    payment4?: VrboPaymentSchedule;
    /**
     * 
     * @type {VrboPaymentSchedule}
     * @memberof VrboSettingsPostPropertiesRoomTypesInnerPaymentSchedules
     */
    payment5?: VrboPaymentSchedule;
}

/**
 * Check if a given object implements the VrboSettingsPostPropertiesRoomTypesInnerPaymentSchedules interface.
 */
export function instanceOfVrboSettingsPostPropertiesRoomTypesInnerPaymentSchedules(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VrboSettingsPostPropertiesRoomTypesInnerPaymentSchedulesFromJSON(json: any): VrboSettingsPostPropertiesRoomTypesInnerPaymentSchedules {
    return VrboSettingsPostPropertiesRoomTypesInnerPaymentSchedulesFromJSONTyped(json, false);
}

export function VrboSettingsPostPropertiesRoomTypesInnerPaymentSchedulesFromJSONTyped(json: any, ignoreDiscriminator: boolean): VrboSettingsPostPropertiesRoomTypesInnerPaymentSchedules {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'payment1': !exists(json, 'payment1') ? undefined : VrboPaymentScheduleFromJSON(json['payment1']),
        'payment2': !exists(json, 'payment2') ? undefined : VrboPaymentScheduleFromJSON(json['payment2']),
        'payment3': !exists(json, 'payment3') ? undefined : VrboPaymentScheduleFromJSON(json['payment3']),
        'payment4': !exists(json, 'payment4') ? undefined : VrboPaymentScheduleFromJSON(json['payment4']),
        'payment5': !exists(json, 'payment5') ? undefined : VrboPaymentScheduleFromJSON(json['payment5']),
    };
}

export function VrboSettingsPostPropertiesRoomTypesInnerPaymentSchedulesToJSON(value?: VrboSettingsPostPropertiesRoomTypesInnerPaymentSchedules | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'payment1': VrboPaymentScheduleToJSON(value.payment1),
        'payment2': VrboPaymentScheduleToJSON(value.payment2),
        'payment3': VrboPaymentScheduleToJSON(value.payment3),
        'payment4': VrboPaymentScheduleToJSON(value.payment4),
        'payment5': VrboPaymentScheduleToJSON(value.payment5),
    };
}

