/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VrboSettingsPostPropertiesRoomTypesInnerPriceRulesInner
 */
export interface VrboSettingsPostPropertiesRoomTypesInnerPriceRulesInner {
    /**
     * 
     * @type {number}
     * @memberof VrboSettingsPostPropertiesRoomTypesInnerPriceRulesInner
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof VrboSettingsPostPropertiesRoomTypesInnerPriceRulesInner
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the VrboSettingsPostPropertiesRoomTypesInnerPriceRulesInner interface.
 */
export function instanceOfVrboSettingsPostPropertiesRoomTypesInnerPriceRulesInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VrboSettingsPostPropertiesRoomTypesInnerPriceRulesInnerFromJSON(json: any): VrboSettingsPostPropertiesRoomTypesInnerPriceRulesInner {
    return VrboSettingsPostPropertiesRoomTypesInnerPriceRulesInnerFromJSONTyped(json, false);
}

export function VrboSettingsPostPropertiesRoomTypesInnerPriceRulesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): VrboSettingsPostPropertiesRoomTypesInnerPriceRulesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
    };
}

export function VrboSettingsPostPropertiesRoomTypesInnerPriceRulesInnerToJSON(value?: VrboSettingsPostPropertiesRoomTypesInnerPriceRulesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'enabled': value.enabled,
    };
}

