/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VrboSettingsPostPropertiesRoomTypesInner } from './VrboSettingsPostPropertiesRoomTypesInner';
import {
    VrboSettingsPostPropertiesRoomTypesInnerFromJSON,
    VrboSettingsPostPropertiesRoomTypesInnerFromJSONTyped,
    VrboSettingsPostPropertiesRoomTypesInnerToJSON,
} from './VrboSettingsPostPropertiesRoomTypesInner';
import type { VrboSettingsPostPropertiesSpecificPropertyContent } from './VrboSettingsPostPropertiesSpecificPropertyContent';
import {
    VrboSettingsPostPropertiesSpecificPropertyContentFromJSON,
    VrboSettingsPostPropertiesSpecificPropertyContentFromJSONTyped,
    VrboSettingsPostPropertiesSpecificPropertyContentToJSON,
} from './VrboSettingsPostPropertiesSpecificPropertyContent';
import type { VrboSettingsPostPropertiesVrboICal } from './VrboSettingsPostPropertiesVrboICal';
import {
    VrboSettingsPostPropertiesVrboICalFromJSON,
    VrboSettingsPostPropertiesVrboICalFromJSONTyped,
    VrboSettingsPostPropertiesVrboICalToJSON,
} from './VrboSettingsPostPropertiesVrboICal';

/**
 * 
 * @export
 * @interface VrboSettingsPostProperties
 */
export interface VrboSettingsPostProperties {
    /**
     * 
     * @type {number}
     * @memberof VrboSettingsPostProperties
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof VrboSettingsPostProperties
     */
    priceMultiplier?: number;
    /**
     * 
     * @type {string}
     * @memberof VrboSettingsPostProperties
     */
    invoiceeId?: string | null;
    /**
     * 
     * @type {VrboSettingsPostPropertiesSpecificPropertyContent}
     * @memberof VrboSettingsPostProperties
     */
    specificPropertyContent?: VrboSettingsPostPropertiesSpecificPropertyContent;
    /**
     * 
     * @type {VrboSettingsPostPropertiesVrboICal}
     * @memberof VrboSettingsPostProperties
     */
    vrboICal?: VrboSettingsPostPropertiesVrboICal;
    /**
     * 
     * @type {Array<VrboSettingsPostPropertiesRoomTypesInner>}
     * @memberof VrboSettingsPostProperties
     */
    roomTypes?: Array<VrboSettingsPostPropertiesRoomTypesInner>;
}

/**
 * Check if a given object implements the VrboSettingsPostProperties interface.
 */
export function instanceOfVrboSettingsPostProperties(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VrboSettingsPostPropertiesFromJSON(json: any): VrboSettingsPostProperties {
    return VrboSettingsPostPropertiesFromJSONTyped(json, false);
}

export function VrboSettingsPostPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): VrboSettingsPostProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'priceMultiplier': !exists(json, 'priceMultiplier') ? undefined : json['priceMultiplier'],
        'invoiceeId': !exists(json, 'invoiceeId') ? undefined : json['invoiceeId'],
        'specificPropertyContent': !exists(json, 'specificPropertyContent') ? undefined : VrboSettingsPostPropertiesSpecificPropertyContentFromJSON(json['specificPropertyContent']),
        'vrboICal': !exists(json, 'vrboICal') ? undefined : VrboSettingsPostPropertiesVrboICalFromJSON(json['vrboICal']),
        'roomTypes': !exists(json, 'roomTypes') ? undefined : ((json['roomTypes'] as Array<any>).map(VrboSettingsPostPropertiesRoomTypesInnerFromJSON)),
    };
}

export function VrboSettingsPostPropertiesToJSON(value?: VrboSettingsPostProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'priceMultiplier': value.priceMultiplier,
        'invoiceeId': value.invoiceeId,
        'specificPropertyContent': VrboSettingsPostPropertiesSpecificPropertyContentToJSON(value.specificPropertyContent),
        'vrboICal': VrboSettingsPostPropertiesVrboICalToJSON(value.vrboICal),
        'roomTypes': value.roomTypes === undefined ? undefined : ((value.roomTypes as Array<any>).map(VrboSettingsPostPropertiesRoomTypesInnerToJSON)),
    };
}

