/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VrboSettingsPostPropertiesSpecificPropertyContent
 */
export interface VrboSettingsPostPropertiesSpecificPropertyContent {
    /**
     * 
     * @type {string}
     * @memberof VrboSettingsPostPropertiesSpecificPropertyContent
     */
    defaultLanguage?: VrboSettingsPostPropertiesSpecificPropertyContentDefaultLanguageEnum;
    /**
     * 
     * @type {boolean}
     * @memberof VrboSettingsPostPropertiesSpecificPropertyContent
     */
    showExactLanguage?: boolean;
    /**
     * 
     * @type {string}
     * @memberof VrboSettingsPostPropertiesSpecificPropertyContent
     */
    ownerListingStory?: string;
    /**
     * 
     * @type {string}
     * @memberof VrboSettingsPostPropertiesSpecificPropertyContent
     */
    uniqueBenefits?: string;
    /**
     * 
     * @type {string}
     * @memberof VrboSettingsPostPropertiesSpecificPropertyContent
     */
    whyPurchased?: string;
    /**
     * 
     * @type {string}
     * @memberof VrboSettingsPostPropertiesSpecificPropertyContent
     */
    yearPurchased?: string;
    /**
     * 
     * @type {string}
     * @memberof VrboSettingsPostPropertiesSpecificPropertyContent
     */
    acceptedPaymentType?: VrboSettingsPostPropertiesSpecificPropertyContentAcceptedPaymentTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof VrboSettingsPostPropertiesSpecificPropertyContent
     */
    paymentInvoiceDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof VrboSettingsPostPropertiesSpecificPropertyContent
     */
    paymentSchedule?: VrboSettingsPostPropertiesSpecificPropertyContentPaymentScheduleEnum;
    /**
     * 
     * @type {string}
     * @memberof VrboSettingsPostPropertiesSpecificPropertyContent
     */
    merchantName?: string;
}


/**
 * @export
 */
export const VrboSettingsPostPropertiesSpecificPropertyContentDefaultLanguageEnum = {
    De: 'de',
    En: 'en',
    Es: 'es',
    Fi: 'fi',
    Fr: 'fr',
    It: 'it',
    Ja: 'ja',
    Nl: 'nl',
    No: 'no',
    Pt: 'pt',
    Sov: 'sov'
} as const;
export type VrboSettingsPostPropertiesSpecificPropertyContentDefaultLanguageEnum = typeof VrboSettingsPostPropertiesSpecificPropertyContentDefaultLanguageEnum[keyof typeof VrboSettingsPostPropertiesSpecificPropertyContentDefaultLanguageEnum];

/**
 * @export
 */
export const VrboSettingsPostPropertiesSpecificPropertyContentAcceptedPaymentTypeEnum = {
    All: 'all',
    InvoiceOnly: 'invoiceOnly',
    CardOnly: 'cardOnly'
} as const;
export type VrboSettingsPostPropertiesSpecificPropertyContentAcceptedPaymentTypeEnum = typeof VrboSettingsPostPropertiesSpecificPropertyContentAcceptedPaymentTypeEnum[keyof typeof VrboSettingsPostPropertiesSpecificPropertyContentAcceptedPaymentTypeEnum];

/**
 * @export
 */
export const VrboSettingsPostPropertiesSpecificPropertyContentPaymentScheduleEnum = {
    AtCheckin: 'atCheckin',
    AtBooking: 'atBooking'
} as const;
export type VrboSettingsPostPropertiesSpecificPropertyContentPaymentScheduleEnum = typeof VrboSettingsPostPropertiesSpecificPropertyContentPaymentScheduleEnum[keyof typeof VrboSettingsPostPropertiesSpecificPropertyContentPaymentScheduleEnum];


/**
 * Check if a given object implements the VrboSettingsPostPropertiesSpecificPropertyContent interface.
 */
export function instanceOfVrboSettingsPostPropertiesSpecificPropertyContent(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VrboSettingsPostPropertiesSpecificPropertyContentFromJSON(json: any): VrboSettingsPostPropertiesSpecificPropertyContent {
    return VrboSettingsPostPropertiesSpecificPropertyContentFromJSONTyped(json, false);
}

export function VrboSettingsPostPropertiesSpecificPropertyContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): VrboSettingsPostPropertiesSpecificPropertyContent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'defaultLanguage': !exists(json, 'defaultLanguage') ? undefined : json['defaultLanguage'],
        'showExactLanguage': !exists(json, 'showExactLanguage') ? undefined : json['showExactLanguage'],
        'ownerListingStory': !exists(json, 'ownerListingStory') ? undefined : json['ownerListingStory'],
        'uniqueBenefits': !exists(json, 'uniqueBenefits') ? undefined : json['uniqueBenefits'],
        'whyPurchased': !exists(json, 'whyPurchased') ? undefined : json['whyPurchased'],
        'yearPurchased': !exists(json, 'yearPurchased') ? undefined : json['yearPurchased'],
        'acceptedPaymentType': !exists(json, 'acceptedPaymentType') ? undefined : json['acceptedPaymentType'],
        'paymentInvoiceDescription': !exists(json, 'paymentInvoiceDescription') ? undefined : json['paymentInvoiceDescription'],
        'paymentSchedule': !exists(json, 'paymentSchedule') ? undefined : json['paymentSchedule'],
        'merchantName': !exists(json, 'merchantName') ? undefined : json['merchantName'],
    };
}

export function VrboSettingsPostPropertiesSpecificPropertyContentToJSON(value?: VrboSettingsPostPropertiesSpecificPropertyContent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'defaultLanguage': value.defaultLanguage,
        'showExactLanguage': value.showExactLanguage,
        'ownerListingStory': value.ownerListingStory,
        'uniqueBenefits': value.uniqueBenefits,
        'whyPurchased': value.whyPurchased,
        'yearPurchased': value.yearPurchased,
        'acceptedPaymentType': value.acceptedPaymentType,
        'paymentInvoiceDescription': value.paymentInvoiceDescription,
        'paymentSchedule': value.paymentSchedule,
        'merchantName': value.merchantName,
    };
}

