/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VrboSettingsPostPropertiesRoomTypesInnerVrboICal
 */
export interface VrboSettingsPostPropertiesRoomTypesInnerVrboICal {
    /**
     * 
     * @type {string}
     * @memberof VrboSettingsPostPropertiesRoomTypesInnerVrboICal
     */
    exportCalendar?: string;
    /**
     * 
     * @type {boolean}
     * @memberof VrboSettingsPostPropertiesRoomTypesInnerVrboICal
     */
    syncInventory?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VrboSettingsPostPropertiesRoomTypesInnerVrboICal
     */
    syncBookings?: boolean;
}

/**
 * Check if a given object implements the VrboSettingsPostPropertiesRoomTypesInnerVrboICal interface.
 */
export function instanceOfVrboSettingsPostPropertiesRoomTypesInnerVrboICal(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VrboSettingsPostPropertiesRoomTypesInnerVrboICalFromJSON(json: any): VrboSettingsPostPropertiesRoomTypesInnerVrboICal {
    return VrboSettingsPostPropertiesRoomTypesInnerVrboICalFromJSONTyped(json, false);
}

export function VrboSettingsPostPropertiesRoomTypesInnerVrboICalFromJSONTyped(json: any, ignoreDiscriminator: boolean): VrboSettingsPostPropertiesRoomTypesInnerVrboICal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'exportCalendar': !exists(json, 'exportCalendar') ? undefined : json['exportCalendar'],
        'syncInventory': !exists(json, 'syncInventory') ? undefined : json['syncInventory'],
        'syncBookings': !exists(json, 'syncBookings') ? undefined : json['syncBookings'],
    };
}

export function VrboSettingsPostPropertiesRoomTypesInnerVrboICalToJSON(value?: VrboSettingsPostPropertiesRoomTypesInnerVrboICal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'exportCalendar': value.exportCalendar,
        'syncInventory': value.syncInventory,
        'syncBookings': value.syncBookings,
    };
}

