/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountSearchCriteriaInnerCategoryLabel } from './AccountSearchCriteriaInnerCategoryLabel';
import {
    AccountSearchCriteriaInnerCategoryLabelFromJSON,
    AccountSearchCriteriaInnerCategoryLabelFromJSONTyped,
    AccountSearchCriteriaInnerCategoryLabelToJSON,
} from './AccountSearchCriteriaInnerCategoryLabel';

/**
 * 
 * @export
 * @interface AccountSearchCriteriaInner
 */
export interface AccountSearchCriteriaInner {
    /**
     * 
     * @type {number}
     * @memberof AccountSearchCriteriaInner
     */
    index?: number;
    /**
     * 
     * @type {string}
     * @memberof AccountSearchCriteriaInner
     */
    type?: AccountSearchCriteriaInnerTypeEnum;
    /**
     * 
     * @type {AccountSearchCriteriaInnerCategoryLabel}
     * @memberof AccountSearchCriteriaInner
     */
    categoryLabel?: AccountSearchCriteriaInnerCategoryLabel;
    /**
     * 
     * @type {AccountSearchCriteriaInnerCategoryLabel}
     * @memberof AccountSearchCriteriaInner
     */
    searchTerms?: AccountSearchCriteriaInnerCategoryLabel;
}


/**
 * @export
 */
export const AccountSearchCriteriaInnerTypeEnum = {
    NotUsed: 'notUsed',
    SelectorUpper: 'selectorUpper',
    SelectorLower: 'selectorLower',
    CheckboxHorizontalUpper: 'checkboxHorizontalUpper',
    CheckboxHorizontalLower: 'checkboxHorizontalLower',
    CheckboxVerticalUpper: 'checkboxVerticalUpper',
    CheckboxVerticalLower: 'checkboxVerticalLower'
} as const;
export type AccountSearchCriteriaInnerTypeEnum = typeof AccountSearchCriteriaInnerTypeEnum[keyof typeof AccountSearchCriteriaInnerTypeEnum];


/**
 * Check if a given object implements the AccountSearchCriteriaInner interface.
 */
export function instanceOfAccountSearchCriteriaInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccountSearchCriteriaInnerFromJSON(json: any): AccountSearchCriteriaInner {
    return AccountSearchCriteriaInnerFromJSONTyped(json, false);
}

export function AccountSearchCriteriaInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountSearchCriteriaInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'index': !exists(json, 'index') ? undefined : json['index'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'categoryLabel': !exists(json, 'categoryLabel') ? undefined : AccountSearchCriteriaInnerCategoryLabelFromJSON(json['categoryLabel']),
        'searchTerms': !exists(json, 'searchTerms') ? undefined : AccountSearchCriteriaInnerCategoryLabelFromJSON(json['searchTerms']),
    };
}

export function AccountSearchCriteriaInnerToJSON(value?: AccountSearchCriteriaInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'index': value.index,
        'type': value.type,
        'categoryLabel': AccountSearchCriteriaInnerCategoryLabelToJSON(value.categoryLabel),
        'searchTerms': AccountSearchCriteriaInnerCategoryLabelToJSON(value.searchTerms),
    };
}

