/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountSearchCriteriaInnerCategoryLabel
 */
export interface AccountSearchCriteriaInnerCategoryLabel {
    /**
     * 
     * @type {string}
     * @memberof AccountSearchCriteriaInnerCategoryLabel
     */
    en?: string;
}

/**
 * Check if a given object implements the AccountSearchCriteriaInnerCategoryLabel interface.
 */
export function instanceOfAccountSearchCriteriaInnerCategoryLabel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccountSearchCriteriaInnerCategoryLabelFromJSON(json: any): AccountSearchCriteriaInnerCategoryLabel {
    return AccountSearchCriteriaInnerCategoryLabelFromJSONTyped(json, false);
}

export function AccountSearchCriteriaInnerCategoryLabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountSearchCriteriaInnerCategoryLabel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'en': !exists(json, 'en') ? undefined : json['en'],
    };
}

export function AccountSearchCriteriaInnerCategoryLabelToJSON(value?: AccountSearchCriteriaInnerCategoryLabel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'en': value.en,
    };
}

