/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AirbnbListingAirbnbListing } from './AirbnbListingAirbnbListing';
import {
    AirbnbListingAirbnbListingFromJSON,
    AirbnbListingAirbnbListingFromJSONTyped,
    AirbnbListingAirbnbListingToJSON,
} from './AirbnbListingAirbnbListing';

/**
 * 
 * @export
 * @interface AirbnbListing
 */
export interface AirbnbListing {
    /**
     * 
     * @type {number}
     * @memberof AirbnbListing
     */
    roomId?: number;
    /**
     * 
     * @type {string}
     * @memberof AirbnbListing
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AirbnbListing
     */
    enabled?: boolean;
    /**
     * 
     * @type {AirbnbListingAirbnbListing}
     * @memberof AirbnbListing
     */
    airbnbListing?: AirbnbListingAirbnbListing;
}

/**
 * Check if a given object implements the AirbnbListing interface.
 */
export function instanceOfAirbnbListing(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AirbnbListingFromJSON(json: any): AirbnbListing {
    return AirbnbListingFromJSONTyped(json, false);
}

export function AirbnbListingFromJSONTyped(json: any, ignoreDiscriminator: boolean): AirbnbListing {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roomId': !exists(json, 'roomId') ? undefined : json['roomId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'airbnbListing': !exists(json, 'airbnbListing') ? undefined : AirbnbListingAirbnbListingFromJSON(json['airbnbListing']),
    };
}

export function AirbnbListingToJSON(value?: AirbnbListing | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'roomId': value.roomId,
        'name': value.name,
        'enabled': value.enabled,
        'airbnbListing': AirbnbListingAirbnbListingToJSON(value.airbnbListing),
    };
}

