/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AirbnbSettingsPostPropertiesInner } from './AirbnbSettingsPostPropertiesInner';
import {
    AirbnbSettingsPostPropertiesInnerFromJSON,
    AirbnbSettingsPostPropertiesInnerFromJSONTyped,
    AirbnbSettingsPostPropertiesInnerToJSON,
} from './AirbnbSettingsPostPropertiesInner';

/**
 * 
 * @export
 * @interface AirbnbSettingsPost
 */
export interface AirbnbSettingsPost {
    /**
     * 
     * @type {string}
     * @memberof AirbnbSettingsPost
     */
    channel?: string;
    /**
     * 
     * @type {Array<AirbnbSettingsPostPropertiesInner>}
     * @memberof AirbnbSettingsPost
     */
    properties?: Array<AirbnbSettingsPostPropertiesInner>;
}

/**
 * Check if a given object implements the AirbnbSettingsPost interface.
 */
export function instanceOfAirbnbSettingsPost(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AirbnbSettingsPostFromJSON(json: any): AirbnbSettingsPost {
    return AirbnbSettingsPostFromJSONTyped(json, false);
}

export function AirbnbSettingsPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): AirbnbSettingsPost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channel': !exists(json, 'channel') ? undefined : json['channel'],
        'properties': !exists(json, 'properties') ? undefined : ((json['properties'] as Array<any>).map(AirbnbSettingsPostPropertiesInnerFromJSON)),
    };
}

export function AirbnbSettingsPostToJSON(value?: AirbnbSettingsPost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel': value.channel,
        'properties': value.properties === undefined ? undefined : ((value.properties as Array<any>).map(AirbnbSettingsPostPropertiesInnerToJSON)),
    };
}

