/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AirbnbListingAirbnbListingAmenitiesInnerAMENITYNAME } from './AirbnbListingAirbnbListingAmenitiesInnerAMENITYNAME';
import {
    AirbnbListingAirbnbListingAmenitiesInnerAMENITYNAMEFromJSON,
    AirbnbListingAirbnbListingAmenitiesInnerAMENITYNAMEFromJSONTyped,
    AirbnbListingAirbnbListingAmenitiesInnerAMENITYNAMEToJSON,
} from './AirbnbListingAirbnbListingAmenitiesInnerAMENITYNAME';

/**
 * 
 * @export
 * @interface AirbnbListingAirbnbListingAmenitiesInner
 */
export interface AirbnbListingAirbnbListingAmenitiesInner {
    /**
     * 
     * @type {AirbnbListingAirbnbListingAmenitiesInnerAMENITYNAME}
     * @memberof AirbnbListingAirbnbListingAmenitiesInner
     */
    aMENITYNAME?: AirbnbListingAirbnbListingAmenitiesInnerAMENITYNAME;
}

/**
 * Check if a given object implements the AirbnbListingAirbnbListingAmenitiesInner interface.
 */
export function instanceOfAirbnbListingAirbnbListingAmenitiesInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AirbnbListingAirbnbListingAmenitiesInnerFromJSON(json: any): AirbnbListingAirbnbListingAmenitiesInner {
    return AirbnbListingAirbnbListingAmenitiesInnerFromJSONTyped(json, false);
}

export function AirbnbListingAirbnbListingAmenitiesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AirbnbListingAirbnbListingAmenitiesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aMENITYNAME': !exists(json, 'AMENITY_NAME') ? undefined : AirbnbListingAirbnbListingAmenitiesInnerAMENITYNAMEFromJSON(json['AMENITY_NAME']),
    };
}

export function AirbnbListingAirbnbListingAmenitiesInnerToJSON(value?: AirbnbListingAirbnbListingAmenitiesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AMENITY_NAME': AirbnbListingAirbnbListingAmenitiesInnerAMENITYNAMEToJSON(value.aMENITYNAME),
    };
}

