/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AirbnbSettingsPostPropertiesInnerRoomTypesInner } from './AirbnbSettingsPostPropertiesInnerRoomTypesInner';
import {
    AirbnbSettingsPostPropertiesInnerRoomTypesInnerFromJSON,
    AirbnbSettingsPostPropertiesInnerRoomTypesInnerFromJSONTyped,
    AirbnbSettingsPostPropertiesInnerRoomTypesInnerToJSON,
} from './AirbnbSettingsPostPropertiesInnerRoomTypesInner';

/**
 * 
 * @export
 * @interface AirbnbSettingsPostPropertiesInner
 */
export interface AirbnbSettingsPostPropertiesInner {
    /**
     * 
     * @type {number}
     * @memberof AirbnbSettingsPostPropertiesInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AirbnbSettingsPostPropertiesInner
     */
    multiplier?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AirbnbSettingsPostPropertiesInner
     */
    currency?: AirbnbSettingsPostPropertiesInnerCurrencyEnum;
    /**
     * 
     * @type {string}
     * @memberof AirbnbSettingsPostPropertiesInner
     */
    inquiryAndRequests?: AirbnbSettingsPostPropertiesInnerInquiryAndRequestsEnum;
    /**
     * 
     * @type {string}
     * @memberof AirbnbSettingsPostPropertiesInner
     */
    invoiceeId?: string | null;
    /**
     * 
     * @type {Array<AirbnbSettingsPostPropertiesInnerRoomTypesInner>}
     * @memberof AirbnbSettingsPostPropertiesInner
     */
    roomTypes?: Array<AirbnbSettingsPostPropertiesInnerRoomTypesInner>;
}


/**
 * @export
 */
export const AirbnbSettingsPostPropertiesInnerCurrencyEnum = {
    Aed: 'AED',
    All: 'ALL',
    Amd: 'AMD',
    Ars: 'ARS',
    Aud: 'AUD',
    Azn: 'AZN',
    Bdt: 'BDT',
    Bgn: 'BGN',
    Bhd: 'BHD',
    Bnd: 'BND',
    Brl: 'BRL',
    Cad: 'CAD',
    Chf: 'CHF',
    Clp: 'CLP',
    Cny: 'CNY',
    Cop: 'COP',
    Crc: 'CRC',
    Czk: 'CZK',
    Dkk: 'DKK',
    Dop: 'DOP',
    Egp: 'EGP',
    Eur: 'EUR',
    Fjd: 'FJD',
    Gbp: 'GBP',
    Gel: 'GEL',
    Hkd: 'HKD',
    Hrk: 'HRK',
    Huf: 'HUF',
    Inr: 'INR',
    Idr: 'IDR',
    Irr: 'IRR',
    Ils: 'ILS',
    Isk: 'ISK',
    Jod: 'JOD',
    Jpy: 'JPY',
    Kes: 'KES',
    Krw: 'KRW',
    Lbp: 'LBP',
    Lkr: 'LKR',
    Mad: 'MAD',
    Mmk: 'MMK',
    Mxn: 'MXN',
    Myr: 'MYR',
    Mzn: 'MZN',
    Nok: 'NOK',
    Nzd: 'NZD',
    Omr: 'OMR',
    Php: 'PHP',
    Pln: 'PLN',
    Ron: 'RON',
    Rsd: 'RSD',
    Rub: 'RUB',
    Sar: 'SAR',
    Sek: 'SEK',
    Sgd: 'SGD',
    Twd: 'TWD',
    Thb: 'THB',
    Tnd: 'TND',
    Try: 'TRY',
    Tzs: 'TZS',
    Uah: 'UAH',
    Usd: 'USD',
    Vnd: 'VND',
    Xof: 'XOF',
    Xpf: 'XPF',
    Yer: 'YER',
    Zar: 'ZAR'
} as const;
export type AirbnbSettingsPostPropertiesInnerCurrencyEnum = typeof AirbnbSettingsPostPropertiesInnerCurrencyEnum[keyof typeof AirbnbSettingsPostPropertiesInnerCurrencyEnum];

/**
 * @export
 */
export const AirbnbSettingsPostPropertiesInnerInquiryAndRequestsEnum = {
    Ignore: 'ignore',
    ImportAll: 'importAll',
    ImportOnlyContainingBookingNumber: 'importOnlyContainingBookingNumber'
} as const;
export type AirbnbSettingsPostPropertiesInnerInquiryAndRequestsEnum = typeof AirbnbSettingsPostPropertiesInnerInquiryAndRequestsEnum[keyof typeof AirbnbSettingsPostPropertiesInnerInquiryAndRequestsEnum];


/**
 * Check if a given object implements the AirbnbSettingsPostPropertiesInner interface.
 */
export function instanceOfAirbnbSettingsPostPropertiesInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AirbnbSettingsPostPropertiesInnerFromJSON(json: any): AirbnbSettingsPostPropertiesInner {
    return AirbnbSettingsPostPropertiesInnerFromJSONTyped(json, false);
}

export function AirbnbSettingsPostPropertiesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AirbnbSettingsPostPropertiesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'multiplier': !exists(json, 'multiplier') ? undefined : json['multiplier'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'inquiryAndRequests': !exists(json, 'inquiryAndRequests') ? undefined : json['inquiryAndRequests'],
        'invoiceeId': !exists(json, 'invoiceeId') ? undefined : json['invoiceeId'],
        'roomTypes': !exists(json, 'roomTypes') ? undefined : ((json['roomTypes'] as Array<any>).map(AirbnbSettingsPostPropertiesInnerRoomTypesInnerFromJSON)),
    };
}

export function AirbnbSettingsPostPropertiesInnerToJSON(value?: AirbnbSettingsPostPropertiesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'multiplier': value.multiplier,
        'currency': value.currency,
        'inquiryAndRequests': value.inquiryAndRequests,
        'invoiceeId': value.invoiceeId,
        'roomTypes': value.roomTypes === undefined ? undefined : ((value.roomTypes as Array<any>).map(AirbnbSettingsPostPropertiesInnerRoomTypesInnerToJSON)),
    };
}

