/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BookingGuestsGuestsInner } from './BookingGuestsGuestsInner';
import {
    BookingGuestsGuestsInnerFromJSON,
    BookingGuestsGuestsInnerFromJSONTyped,
    BookingGuestsGuestsInnerToJSON,
} from './BookingGuestsGuestsInner';

/**
 * 
 * @export
 * @interface BookingGuests
 */
export interface BookingGuests {
    /**
     * Coming soon - Requires the bookings-personal scope
     * @type {Array<BookingGuestsGuestsInner>}
     * @memberof BookingGuests
     */
    guests?: Array<BookingGuestsGuestsInner>;
}

/**
 * Check if a given object implements the BookingGuests interface.
 */
export function instanceOfBookingGuests(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookingGuestsFromJSON(json: any): BookingGuests {
    return BookingGuestsFromJSONTyped(json, false);
}

export function BookingGuestsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingGuests {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'guests': !exists(json, 'guests') ? undefined : ((json['guests'] as Array<any>).map(BookingGuestsGuestsInnerFromJSON)),
    };
}

export function BookingGuestsToJSON(value?: BookingGuests | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'guests': value.guests === undefined ? undefined : ((value.guests as Array<any>).map(BookingGuestsGuestsInnerToJSON)),
    };
}

