/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BookingActionsActions } from './BookingActionsActions';
import {
    BookingActionsActionsFromJSON,
    BookingActionsActionsFromJSONTyped,
    BookingActionsActionsToJSON,
} from './BookingActionsActions';

/**
 * 
 * @export
 * @interface BookingActions
 */
export interface BookingActions {
    /**
     * 
     * @type {BookingActionsActions}
     * @memberof BookingActions
     */
    actions?: BookingActionsActions;
}

/**
 * Check if a given object implements the BookingActions interface.
 */
export function instanceOfBookingActions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookingActionsFromJSON(json: any): BookingActions {
    return BookingActionsFromJSONTyped(json, false);
}

export function BookingActionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingActions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'actions': !exists(json, 'actions') ? undefined : BookingActionsActionsFromJSON(json['actions']),
    };
}

export function BookingActionsToJSON(value?: BookingActions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'actions': BookingActionsActionsToJSON(value.actions),
    };
}

