/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookingAllOfAllowCancellation
 */
export interface BookingAllOfAllowCancellation {
    /**
     * 
     * @type {string}
     * @memberof BookingAllOfAllowCancellation
     */
    type?: BookingAllOfAllowCancellationTypeEnum;
    /**
     * Used to specify the number of days if type is set to daysBeforeArrival
     * @type {number}
     * @memberof BookingAllOfAllowCancellation
     */
    daysBeforeArrivalValue?: number | null;
}


/**
 * @export
 */
export const BookingAllOfAllowCancellationTypeEnum = {
    PropertyDefault: 'propertyDefault',
    Never: 'never',
    Always: 'always',
    DaysBeforeArrival: 'daysBeforeArrival'
} as const;
export type BookingAllOfAllowCancellationTypeEnum = typeof BookingAllOfAllowCancellationTypeEnum[keyof typeof BookingAllOfAllowCancellationTypeEnum];


/**
 * Check if a given object implements the BookingAllOfAllowCancellation interface.
 */
export function instanceOfBookingAllOfAllowCancellation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookingAllOfAllowCancellationFromJSON(json: any): BookingAllOfAllowCancellation {
    return BookingAllOfAllowCancellationFromJSONTyped(json, false);
}

export function BookingAllOfAllowCancellationFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingAllOfAllowCancellation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'daysBeforeArrivalValue': !exists(json, 'daysBeforeArrivalValue') ? undefined : json['daysBeforeArrivalValue'],
    };
}

export function BookingAllOfAllowCancellationToJSON(value?: BookingAllOfAllowCancellation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'daysBeforeArrivalValue': value.daysBeforeArrivalValue,
    };
}

