/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BookingActionsActions } from './BookingActionsActions';
import {
    BookingActionsActionsFromJSON,
    BookingActionsActionsFromJSONTyped,
    BookingActionsActionsToJSON,
} from './BookingActionsActions';
import type { Invoice } from './Invoice';
import {
    InvoiceFromJSON,
    InvoiceFromJSONTyped,
    InvoiceToJSON,
} from './Invoice';
import type { NewBookingInfoItemsInner } from './NewBookingInfoItemsInner';
import {
    NewBookingInfoItemsInnerFromJSON,
    NewBookingInfoItemsInnerFromJSONTyped,
    NewBookingInfoItemsInnerToJSON,
} from './NewBookingInfoItemsInner';

/**
 * 
 * @export
 * @interface BookingsPostRequestInner
 */
export interface BookingsPostRequestInner {
    /**
     * 
     * @type {number}
     * @memberof BookingsPostRequestInner
     */
    masterId?: number;
    /**
     * 
     * @type {number}
     * @memberof BookingsPostRequestInner
     */
    roomId: number;
    /**
     * 
     * @type {number}
     * @memberof BookingsPostRequestInner
     */
    unitId?: number;
    /**
     * 
     * @type {number}
     * @memberof BookingsPostRequestInner
     */
    roomQty?: number;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    status?: BookingsPostRequestInnerStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof BookingsPostRequestInner
     */
    arrival: Date;
    /**
     * 
     * @type {Date}
     * @memberof BookingsPostRequestInner
     */
    departure: Date;
    /**
     * 
     * @type {number}
     * @memberof BookingsPostRequestInner
     */
    numAdult?: number;
    /**
     * 
     * @type {number}
     * @memberof BookingsPostRequestInner
     */
    numChild?: number;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    mobile?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    fax?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    company?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    postcode?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    country2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    arrivalTime?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    voucher?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    comments?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    groupNote?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    custom1?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    custom2?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    custom3?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    custom4?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    custom5?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    custom6?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    custom7?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    custom8?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    custom9?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    custom10?: string;
    /**
     * Must be a 6 character hexadecimal color or an empty string.
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    flagColor?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    flagText?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    lang?: string;
    /**
     * 
     * @type {number}
     * @memberof BookingsPostRequestInner
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof BookingsPostRequestInner
     */
    deposit?: number;
    /**
     * 
     * @type {number}
     * @memberof BookingsPostRequestInner
     */
    tax?: number;
    /**
     * 
     * @type {number}
     * @memberof BookingsPostRequestInner
     */
    commission?: number;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    refererEditable?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingsPostRequestInner
     */
    rateDescription?: string;
    /**
     * 
     * @type {number}
     * @memberof BookingsPostRequestInner
     */
    invoiceeId?: number | null;
    /**
     * 
     * @type {Array<Invoice>}
     * @memberof BookingsPostRequestInner
     */
    invoiceItems?: Array<Invoice>;
    /**
     * 
     * @type {Array<NewBookingInfoItemsInner>}
     * @memberof BookingsPostRequestInner
     */
    infoItems?: Array<NewBookingInfoItemsInner>;
    /**
     * 
     * @type {BookingActionsActions}
     * @memberof BookingsPostRequestInner
     */
    actions?: BookingActionsActions;
    /**
     * Required to update an existing booking
     * @type {number}
     * @memberof BookingsPostRequestInner
     */
    id?: number;
}


/**
 * @export
 */
export const BookingsPostRequestInnerStatusEnum = {
    Confirmed: 'confirmed',
    Request: 'request',
    New: 'new',
    Cancelled: 'cancelled',
    Black: 'black',
    Inquiry: 'inquiry'
} as const;
export type BookingsPostRequestInnerStatusEnum = typeof BookingsPostRequestInnerStatusEnum[keyof typeof BookingsPostRequestInnerStatusEnum];


/**
 * Check if a given object implements the BookingsPostRequestInner interface.
 */
export function instanceOfBookingsPostRequestInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "roomId" in value;
    isInstance = isInstance && "arrival" in value;
    isInstance = isInstance && "departure" in value;

    return isInstance;
}

export function BookingsPostRequestInnerFromJSON(json: any): BookingsPostRequestInner {
    return BookingsPostRequestInnerFromJSONTyped(json, false);
}

export function BookingsPostRequestInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingsPostRequestInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'masterId': !exists(json, 'masterId') ? undefined : json['masterId'],
        'roomId': json['roomId'],
        'unitId': !exists(json, 'unitId') ? undefined : json['unitId'],
        'roomQty': !exists(json, 'roomQty') ? undefined : json['roomQty'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'arrival': (new Date(json['arrival'])),
        'departure': (new Date(json['departure'])),
        'numAdult': !exists(json, 'numAdult') ? undefined : json['numAdult'],
        'numChild': !exists(json, 'numChild') ? undefined : json['numChild'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'mobile': !exists(json, 'mobile') ? undefined : json['mobile'],
        'fax': !exists(json, 'fax') ? undefined : json['fax'],
        'company': !exists(json, 'company') ? undefined : json['company'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'postcode': !exists(json, 'postcode') ? undefined : json['postcode'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'country2': !exists(json, 'country2') ? undefined : json['country2'],
        'arrivalTime': !exists(json, 'arrivalTime') ? undefined : json['arrivalTime'],
        'voucher': !exists(json, 'voucher') ? undefined : json['voucher'],
        'comments': !exists(json, 'comments') ? undefined : json['comments'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'groupNote': !exists(json, 'groupNote') ? undefined : json['groupNote'],
        'custom1': !exists(json, 'custom1') ? undefined : json['custom1'],
        'custom2': !exists(json, 'custom2') ? undefined : json['custom2'],
        'custom3': !exists(json, 'custom3') ? undefined : json['custom3'],
        'custom4': !exists(json, 'custom4') ? undefined : json['custom4'],
        'custom5': !exists(json, 'custom5') ? undefined : json['custom5'],
        'custom6': !exists(json, 'custom6') ? undefined : json['custom6'],
        'custom7': !exists(json, 'custom7') ? undefined : json['custom7'],
        'custom8': !exists(json, 'custom8') ? undefined : json['custom8'],
        'custom9': !exists(json, 'custom9') ? undefined : json['custom9'],
        'custom10': !exists(json, 'custom10') ? undefined : json['custom10'],
        'flagColor': !exists(json, 'flagColor') ? undefined : json['flagColor'],
        'flagText': !exists(json, 'flagText') ? undefined : json['flagText'],
        'lang': !exists(json, 'lang') ? undefined : json['lang'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'deposit': !exists(json, 'deposit') ? undefined : json['deposit'],
        'tax': !exists(json, 'tax') ? undefined : json['tax'],
        'commission': !exists(json, 'commission') ? undefined : json['commission'],
        'refererEditable': !exists(json, 'refererEditable') ? undefined : json['refererEditable'],
        'rateDescription': !exists(json, 'rateDescription') ? undefined : json['rateDescription'],
        'invoiceeId': !exists(json, 'invoiceeId') ? undefined : json['invoiceeId'],
        'invoiceItems': !exists(json, 'invoiceItems') ? undefined : ((json['invoiceItems'] as Array<any>).map(InvoiceFromJSON)),
        'infoItems': !exists(json, 'infoItems') ? undefined : ((json['infoItems'] as Array<any>).map(NewBookingInfoItemsInnerFromJSON)),
        'actions': !exists(json, 'actions') ? undefined : BookingActionsActionsFromJSON(json['actions']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function BookingsPostRequestInnerToJSON(value?: BookingsPostRequestInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'masterId': value.masterId,
        'roomId': value.roomId,
        'unitId': value.unitId,
        'roomQty': value.roomQty,
        'status': value.status,
        'arrival': (value.arrival.toISOString().substring(0,10)),
        'departure': (value.departure.toISOString().substring(0,10)),
        'numAdult': value.numAdult,
        'numChild': value.numChild,
        'title': value.title,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'email': value.email,
        'phone': value.phone,
        'mobile': value.mobile,
        'fax': value.fax,
        'company': value.company,
        'address': value.address,
        'city': value.city,
        'state': value.state,
        'postcode': value.postcode,
        'country': value.country,
        'country2': value.country2,
        'arrivalTime': value.arrivalTime,
        'voucher': value.voucher,
        'comments': value.comments,
        'notes': value.notes,
        'message': value.message,
        'groupNote': value.groupNote,
        'custom1': value.custom1,
        'custom2': value.custom2,
        'custom3': value.custom3,
        'custom4': value.custom4,
        'custom5': value.custom5,
        'custom6': value.custom6,
        'custom7': value.custom7,
        'custom8': value.custom8,
        'custom9': value.custom9,
        'custom10': value.custom10,
        'flagColor': value.flagColor,
        'flagText': value.flagText,
        'lang': value.lang,
        'price': value.price,
        'deposit': value.deposit,
        'tax': value.tax,
        'commission': value.commission,
        'refererEditable': value.refererEditable,
        'rateDescription': value.rateDescription,
        'invoiceeId': value.invoiceeId,
        'invoiceItems': value.invoiceItems === undefined ? undefined : ((value.invoiceItems as Array<any>).map(InvoiceToJSON)),
        'infoItems': value.infoItems === undefined ? undefined : ((value.infoItems as Array<any>).map(NewBookingInfoItemsInnerToJSON)),
        'actions': BookingActionsActionsToJSON(value.actions),
        'id': value.id,
    };
}

