/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AirbnbSettingsGet } from './AirbnbSettingsGet';
import {
    AirbnbSettingsGetFromJSON,
    AirbnbSettingsGetFromJSONTyped,
    AirbnbSettingsGetToJSON,
} from './AirbnbSettingsGet';
import type { ICalExportSettingsGet } from './ICalExportSettingsGet';
import {
    ICalExportSettingsGetFromJSON,
    ICalExportSettingsGetFromJSONTyped,
    ICalExportSettingsGetToJSON,
} from './ICalExportSettingsGet';
import type { ICalImportSettingsGet } from './ICalImportSettingsGet';
import {
    ICalImportSettingsGetFromJSON,
    ICalImportSettingsGetFromJSONTyped,
    ICalImportSettingsGetToJSON,
} from './ICalImportSettingsGet';
import type { ICalImportSettingsGetPropertiesInner } from './ICalImportSettingsGetPropertiesInner';
import {
    ICalImportSettingsGetPropertiesInnerFromJSON,
    ICalImportSettingsGetPropertiesInnerFromJSONTyped,
    ICalImportSettingsGetPropertiesInnerToJSON,
} from './ICalImportSettingsGetPropertiesInner';

/**
 * 
 * @export
 * @interface ChannelsSettingsGet200ResponseAllOfDataInner
 */
export interface ChannelsSettingsGet200ResponseAllOfDataInner {
    /**
     * 
     * @type {string}
     * @memberof ChannelsSettingsGet200ResponseAllOfDataInner
     */
    channel?: string;
    /**
     * 
     * @type {Array<ICalImportSettingsGetPropertiesInner>}
     * @memberof ChannelsSettingsGet200ResponseAllOfDataInner
     */
    properties?: Array<ICalImportSettingsGetPropertiesInner>;
}

/**
 * Check if a given object implements the ChannelsSettingsGet200ResponseAllOfDataInner interface.
 */
export function instanceOfChannelsSettingsGet200ResponseAllOfDataInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChannelsSettingsGet200ResponseAllOfDataInnerFromJSON(json: any): ChannelsSettingsGet200ResponseAllOfDataInner {
    return ChannelsSettingsGet200ResponseAllOfDataInnerFromJSONTyped(json, false);
}

export function ChannelsSettingsGet200ResponseAllOfDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelsSettingsGet200ResponseAllOfDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channel': !exists(json, 'channel') ? undefined : json['channel'],
        'properties': !exists(json, 'properties') ? undefined : ((json['properties'] as Array<any>).map(ICalImportSettingsGetPropertiesInnerFromJSON)),
    };
}

export function ChannelsSettingsGet200ResponseAllOfDataInnerToJSON(value?: ChannelsSettingsGet200ResponseAllOfDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel': value.channel,
        'properties': value.properties === undefined ? undefined : ((value.properties as Array<any>).map(ICalImportSettingsGetPropertiesInnerToJSON)),
    };
}

