/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ICalExportSettingsPostPropertiesInnerRoomTypesInner
 */
export interface ICalExportSettingsPostPropertiesInnerRoomTypesInner {
    /**
     * 
     * @type {number}
     * @memberof ICalExportSettingsPostPropertiesInnerRoomTypesInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ICalExportSettingsPostPropertiesInnerRoomTypesInner
     */
    iCalRoomDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof ICalExportSettingsPostPropertiesInnerRoomTypesInner
     */
    _export?: ICalExportSettingsPostPropertiesInnerRoomTypesInnerExportEnum;
}


/**
 * @export
 */
export const ICalExportSettingsPostPropertiesInnerRoomTypesInnerExportEnum = {
    Disable: 'disable',
    Bookings: 'bookings',
    UnavailableDates: 'unavailableDates',
    BookingsAndUnavailableDates: 'bookingsAndUnavailableDates'
} as const;
export type ICalExportSettingsPostPropertiesInnerRoomTypesInnerExportEnum = typeof ICalExportSettingsPostPropertiesInnerRoomTypesInnerExportEnum[keyof typeof ICalExportSettingsPostPropertiesInnerRoomTypesInnerExportEnum];


/**
 * Check if a given object implements the ICalExportSettingsPostPropertiesInnerRoomTypesInner interface.
 */
export function instanceOfICalExportSettingsPostPropertiesInnerRoomTypesInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ICalExportSettingsPostPropertiesInnerRoomTypesInnerFromJSON(json: any): ICalExportSettingsPostPropertiesInnerRoomTypesInner {
    return ICalExportSettingsPostPropertiesInnerRoomTypesInnerFromJSONTyped(json, false);
}

export function ICalExportSettingsPostPropertiesInnerRoomTypesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ICalExportSettingsPostPropertiesInnerRoomTypesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'iCalRoomDescription': !exists(json, 'iCalRoomDescription') ? undefined : json['iCalRoomDescription'],
        '_export': !exists(json, 'export') ? undefined : json['export'],
    };
}

export function ICalExportSettingsPostPropertiesInnerRoomTypesInnerToJSON(value?: ICalExportSettingsPostPropertiesInnerRoomTypesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'iCalRoomDescription': value.iCalRoomDescription,
        'export': value._export,
    };
}

