/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MultiplePostResponseErrorsInner } from './MultiplePostResponseErrorsInner';
import {
    MultiplePostResponseErrorsInnerFromJSON,
    MultiplePostResponseErrorsInnerFromJSONTyped,
    MultiplePostResponseErrorsInnerToJSON,
} from './MultiplePostResponseErrorsInner';
import type { MultiplePostResponseNew } from './MultiplePostResponseNew';
import {
    MultiplePostResponseNewFromJSON,
    MultiplePostResponseNewFromJSONTyped,
    MultiplePostResponseNewToJSON,
} from './MultiplePostResponseNew';

/**
 * 
 * @export
 * @interface MultiplePostResponse
 */
export interface MultiplePostResponse {
    /**
     * 
     * @type {boolean}
     * @memberof MultiplePostResponse
     */
    success?: boolean;
    /**
     * 
     * @type {MultiplePostResponseNew}
     * @memberof MultiplePostResponse
     */
    _new?: MultiplePostResponseNew;
    /**
     * 
     * @type {MultiplePostResponseNew}
     * @memberof MultiplePostResponse
     */
    modified?: MultiplePostResponseNew;
    /**
     * 
     * @type {Array<MultiplePostResponseErrorsInner>}
     * @memberof MultiplePostResponse
     */
    errors?: Array<MultiplePostResponseErrorsInner>;
    /**
     * 
     * @type {Array<MultiplePostResponseErrorsInner>}
     * @memberof MultiplePostResponse
     */
    warnings?: Array<MultiplePostResponseErrorsInner>;
    /**
     * 
     * @type {Array<MultiplePostResponseErrorsInner>}
     * @memberof MultiplePostResponse
     */
    info?: Array<MultiplePostResponseErrorsInner>;
}

/**
 * Check if a given object implements the MultiplePostResponse interface.
 */
export function instanceOfMultiplePostResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MultiplePostResponseFromJSON(json: any): MultiplePostResponse {
    return MultiplePostResponseFromJSONTyped(json, false);
}

export function MultiplePostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiplePostResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        '_new': !exists(json, 'new') ? undefined : MultiplePostResponseNewFromJSON(json['new']),
        'modified': !exists(json, 'modified') ? undefined : MultiplePostResponseNewFromJSON(json['modified']),
        'errors': !exists(json, 'errors') ? undefined : ((json['errors'] as Array<any>).map(MultiplePostResponseErrorsInnerFromJSON)),
        'warnings': !exists(json, 'warnings') ? undefined : ((json['warnings'] as Array<any>).map(MultiplePostResponseErrorsInnerFromJSON)),
        'info': !exists(json, 'info') ? undefined : ((json['info'] as Array<any>).map(MultiplePostResponseErrorsInnerFromJSON)),
    };
}

export function MultiplePostResponseToJSON(value?: MultiplePostResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'new': MultiplePostResponseNewToJSON(value._new),
        'modified': MultiplePostResponseNewToJSON(value.modified),
        'errors': value.errors === undefined ? undefined : ((value.errors as Array<any>).map(MultiplePostResponseErrorsInnerToJSON)),
        'warnings': value.warnings === undefined ? undefined : ((value.warnings as Array<any>).map(MultiplePostResponseErrorsInnerToJSON)),
        'info': value.info === undefined ? undefined : ((value.info as Array<any>).map(MultiplePostResponseErrorsInnerToJSON)),
    };
}

