/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MultiplePostResponseNewSubFieldInner
 */
export interface MultiplePostResponseNewSubFieldInner {
    /**
     * 
     * @type {string}
     * @memberof MultiplePostResponseNewSubFieldInner
     */
    field?: string;
}

/**
 * Check if a given object implements the MultiplePostResponseNewSubFieldInner interface.
 */
export function instanceOfMultiplePostResponseNewSubFieldInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MultiplePostResponseNewSubFieldInnerFromJSON(json: any): MultiplePostResponseNewSubFieldInner {
    return MultiplePostResponseNewSubFieldInnerFromJSONTyped(json, false);
}

export function MultiplePostResponseNewSubFieldInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiplePostResponseNewSubFieldInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'field': !exists(json, 'field') ? undefined : json['field'],
    };
}

export function MultiplePostResponseNewSubFieldInnerToJSON(value?: MultiplePostResponseNewSubFieldInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'field': value.field,
    };
}

