/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OfferMinimumStay
 */
export interface OfferMinimumStay {
    /**
     * 
     * @type {string}
     * @memberof OfferMinimumStay
     */
    type?: OfferMinimumStayTypeEnum;
    /**
     * Used to specify the number of days if minimumStay is set to numberOfDays
     * @type {number}
     * @memberof OfferMinimumStay
     */
    numberOfDaysValue?: number | null;
}


/**
 * @export
 */
export const OfferMinimumStayTypeEnum = {
    NumberOfDays: 'numberOfDays',
    Default: 'default'
} as const;
export type OfferMinimumStayTypeEnum = typeof OfferMinimumStayTypeEnum[keyof typeof OfferMinimumStayTypeEnum];


/**
 * Check if a given object implements the OfferMinimumStay interface.
 */
export function instanceOfOfferMinimumStay(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OfferMinimumStayFromJSON(json: any): OfferMinimumStay {
    return OfferMinimumStayFromJSONTyped(json, false);
}

export function OfferMinimumStayFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfferMinimumStay {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'numberOfDaysValue': !exists(json, 'numberOfDaysValue') ? undefined : json['numberOfDaysValue'],
    };
}

export function OfferMinimumStayToJSON(value?: OfferMinimumStay | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'numberOfDaysValue': value.numberOfDaysValue,
    };
}

