/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceRulesBookingPage
 */
export interface PriceRulesBookingPage {
    /**
     * 
     * @type {boolean}
     * @memberof PriceRulesBookingPage
     */
    direct?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PriceRulesBookingPage
     */
    agent?: boolean;
}

/**
 * Check if a given object implements the PriceRulesBookingPage interface.
 */
export function instanceOfPriceRulesBookingPage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PriceRulesBookingPageFromJSON(json: any): PriceRulesBookingPage {
    return PriceRulesBookingPageFromJSONTyped(json, false);
}

export function PriceRulesBookingPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceRulesBookingPage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'direct': !exists(json, 'direct') ? undefined : json['direct'],
        'agent': !exists(json, 'agent') ? undefined : json['agent'],
    };
}

export function PriceRulesBookingPageToJSON(value?: PriceRulesBookingPage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'direct': value.direct,
        'agent': value.agent,
    };
}

