/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PriceRulesChannelsAgoda } from './PriceRulesChannelsAgoda';
import {
    PriceRulesChannelsAgodaFromJSON,
    PriceRulesChannelsAgodaFromJSONTyped,
    PriceRulesChannelsAgodaToJSON,
} from './PriceRulesChannelsAgoda';
import type { PriceRulesChannelsAtraveode } from './PriceRulesChannelsAtraveode';
import {
    PriceRulesChannelsAtraveodeFromJSON,
    PriceRulesChannelsAtraveodeFromJSONTyped,
    PriceRulesChannelsAtraveodeToJSON,
} from './PriceRulesChannelsAtraveode';
import type { PriceRulesChannelsHrs } from './PriceRulesChannelsHrs';
import {
    PriceRulesChannelsHrsFromJSON,
    PriceRulesChannelsHrsFromJSONTyped,
    PriceRulesChannelsHrsToJSON,
} from './PriceRulesChannelsHrs';

/**
 * 
 * @export
 * @interface PriceRulesChannels
 */
export interface PriceRulesChannels {
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    agoda?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    airbnb?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAtraveode}
     * @memberof PriceRulesChannels
     */
    atraveode?: PriceRulesChannelsAtraveode;
    /**
     * 
     * @type {PriceRulesChannelsAtraveode}
     * @memberof PriceRulesChannels
     */
    bedandbreakfasteu?: PriceRulesChannelsAtraveode;
    /**
     * 
     * @type {PriceRulesChannelsAtraveode}
     * @memberof PriceRulesChannels
     */
    bedandbreakfastnl?: PriceRulesChannelsAtraveode;
    /**
     * 
     * @type {PriceRulesChannelsAtraveode}
     * @memberof PriceRulesChannels
     */
    bookeasycomau?: PriceRulesChannelsAtraveode;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    booking?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAtraveode}
     * @memberof PriceRulesChannels
     */
    bookitconz?: PriceRulesChannelsAtraveode;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    trip?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    despegar?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    edreamsodigeo?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    expedia?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    feratel?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAtraveode}
     * @memberof PriceRulesChannels
     */
    flipkey?: PriceRulesChannelsAtraveode;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    goibibo?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAtraveode}
     * @memberof PriceRulesChannels
     */
    guestlinkcouk?: PriceRulesChannelsAtraveode;
    /**
     * 
     * @type {PriceRulesChannelsAtraveode}
     * @memberof PriceRulesChannels
     */
    hometogo?: PriceRulesChannelsAtraveode;
    /**
     * 
     * @type {PriceRulesChannelsAtraveode}
     * @memberof PriceRulesChannels
     */
    hostelinternational?: PriceRulesChannelsAtraveode;
    /**
     * 
     * @type {PriceRulesChannelsAtraveode}
     * @memberof PriceRulesChannels
     */
    hostelsclub?: PriceRulesChannelsAtraveode;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    hostelworld?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    hotelbeds?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsHrs}
     * @memberof PriceRulesChannels
     */
    hrs?: PriceRulesChannelsHrs;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    jomres?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    lastminute?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAtraveode}
     * @memberof PriceRulesChannels
     */
    marriott?: PriceRulesChannelsAtraveode;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    ostrovokru?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    ota?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    reserva?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    tablethotels?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    tiket?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    tomastravel?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAtraveode}
     * @memberof PriceRulesChannels
     */
    traumferienwohnungen?: PriceRulesChannelsAtraveode;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    traveloka?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAgoda}
     * @memberof PriceRulesChannels
     */
    travia?: PriceRulesChannelsAgoda;
    /**
     * 
     * @type {PriceRulesChannelsAtraveode}
     * @memberof PriceRulesChannels
     */
    tripadvisorrentals?: PriceRulesChannelsAtraveode;
    /**
     * 
     * @type {PriceRulesChannelsAtraveode}
     * @memberof PriceRulesChannels
     */
    vacationstay?: PriceRulesChannelsAtraveode;
    /**
     * 
     * @type {PriceRulesChannelsAtraveode}
     * @memberof PriceRulesChannels
     */
    vrbo?: PriceRulesChannelsAtraveode;
    /**
     * 
     * @type {PriceRulesChannelsAtraveode}
     * @memberof PriceRulesChannels
     */
    webroomsconz?: PriceRulesChannelsAtraveode;
}

/**
 * Check if a given object implements the PriceRulesChannels interface.
 */
export function instanceOfPriceRulesChannels(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PriceRulesChannelsFromJSON(json: any): PriceRulesChannels {
    return PriceRulesChannelsFromJSONTyped(json, false);
}

export function PriceRulesChannelsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceRulesChannels {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'agoda': !exists(json, 'agoda') ? undefined : PriceRulesChannelsAgodaFromJSON(json['agoda']),
        'airbnb': !exists(json, 'airbnb') ? undefined : PriceRulesChannelsAgodaFromJSON(json['airbnb']),
        'atraveode': !exists(json, 'atraveode') ? undefined : PriceRulesChannelsAtraveodeFromJSON(json['atraveode']),
        'bedandbreakfasteu': !exists(json, 'bedandbreakfasteu') ? undefined : PriceRulesChannelsAtraveodeFromJSON(json['bedandbreakfasteu']),
        'bedandbreakfastnl': !exists(json, 'bedandbreakfastnl') ? undefined : PriceRulesChannelsAtraveodeFromJSON(json['bedandbreakfastnl']),
        'bookeasycomau': !exists(json, 'bookeasycomau') ? undefined : PriceRulesChannelsAtraveodeFromJSON(json['bookeasycomau']),
        'booking': !exists(json, 'booking') ? undefined : PriceRulesChannelsAgodaFromJSON(json['booking']),
        'bookitconz': !exists(json, 'bookitconz') ? undefined : PriceRulesChannelsAtraveodeFromJSON(json['bookitconz']),
        'trip': !exists(json, 'trip') ? undefined : PriceRulesChannelsAgodaFromJSON(json['trip']),
        'despegar': !exists(json, 'despegar') ? undefined : PriceRulesChannelsAgodaFromJSON(json['despegar']),
        'edreamsodigeo': !exists(json, 'edreamsodigeo') ? undefined : PriceRulesChannelsAgodaFromJSON(json['edreamsodigeo']),
        'expedia': !exists(json, 'expedia') ? undefined : PriceRulesChannelsAgodaFromJSON(json['expedia']),
        'feratel': !exists(json, 'feratel') ? undefined : PriceRulesChannelsAgodaFromJSON(json['feratel']),
        'flipkey': !exists(json, 'flipkey') ? undefined : PriceRulesChannelsAtraveodeFromJSON(json['flipkey']),
        'goibibo': !exists(json, 'goibibo') ? undefined : PriceRulesChannelsAgodaFromJSON(json['goibibo']),
        'guestlinkcouk': !exists(json, 'guestlinkcouk') ? undefined : PriceRulesChannelsAtraveodeFromJSON(json['guestlinkcouk']),
        'hometogo': !exists(json, 'hometogo') ? undefined : PriceRulesChannelsAtraveodeFromJSON(json['hometogo']),
        'hostelinternational': !exists(json, 'hostelinternational') ? undefined : PriceRulesChannelsAtraveodeFromJSON(json['hostelinternational']),
        'hostelsclub': !exists(json, 'hostelsclub') ? undefined : PriceRulesChannelsAtraveodeFromJSON(json['hostelsclub']),
        'hostelworld': !exists(json, 'hostelworld') ? undefined : PriceRulesChannelsAgodaFromJSON(json['hostelworld']),
        'hotelbeds': !exists(json, 'hotelbeds') ? undefined : PriceRulesChannelsAgodaFromJSON(json['hotelbeds']),
        'hrs': !exists(json, 'hrs') ? undefined : PriceRulesChannelsHrsFromJSON(json['hrs']),
        'jomres': !exists(json, 'jomres') ? undefined : PriceRulesChannelsAgodaFromJSON(json['jomres']),
        'lastminute': !exists(json, 'lastminute') ? undefined : PriceRulesChannelsAgodaFromJSON(json['lastminute']),
        'marriott': !exists(json, 'marriott') ? undefined : PriceRulesChannelsAtraveodeFromJSON(json['marriott']),
        'ostrovokru': !exists(json, 'ostrovokru') ? undefined : PriceRulesChannelsAgodaFromJSON(json['ostrovokru']),
        'ota': !exists(json, 'ota') ? undefined : PriceRulesChannelsAgodaFromJSON(json['ota']),
        'reserva': !exists(json, 'reserva') ? undefined : PriceRulesChannelsAgodaFromJSON(json['reserva']),
        'tablethotels': !exists(json, 'tablethotels') ? undefined : PriceRulesChannelsAgodaFromJSON(json['tablethotels']),
        'tiket': !exists(json, 'tiket') ? undefined : PriceRulesChannelsAgodaFromJSON(json['tiket']),
        'tomastravel': !exists(json, 'tomastravel') ? undefined : PriceRulesChannelsAgodaFromJSON(json['tomastravel']),
        'traumferienwohnungen': !exists(json, 'traumferienwohnungen') ? undefined : PriceRulesChannelsAtraveodeFromJSON(json['traumferienwohnungen']),
        'traveloka': !exists(json, 'traveloka') ? undefined : PriceRulesChannelsAgodaFromJSON(json['traveloka']),
        'travia': !exists(json, 'travia') ? undefined : PriceRulesChannelsAgodaFromJSON(json['travia']),
        'tripadvisorrentals': !exists(json, 'tripadvisorrentals') ? undefined : PriceRulesChannelsAtraveodeFromJSON(json['tripadvisorrentals']),
        'vacationstay': !exists(json, 'vacationstay') ? undefined : PriceRulesChannelsAtraveodeFromJSON(json['vacationstay']),
        'vrbo': !exists(json, 'vrbo') ? undefined : PriceRulesChannelsAtraveodeFromJSON(json['vrbo']),
        'webroomsconz': !exists(json, 'webroomsconz') ? undefined : PriceRulesChannelsAtraveodeFromJSON(json['webroomsconz']),
    };
}

export function PriceRulesChannelsToJSON(value?: PriceRulesChannels | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'agoda': PriceRulesChannelsAgodaToJSON(value.agoda),
        'airbnb': PriceRulesChannelsAgodaToJSON(value.airbnb),
        'atraveode': PriceRulesChannelsAtraveodeToJSON(value.atraveode),
        'bedandbreakfasteu': PriceRulesChannelsAtraveodeToJSON(value.bedandbreakfasteu),
        'bedandbreakfastnl': PriceRulesChannelsAtraveodeToJSON(value.bedandbreakfastnl),
        'bookeasycomau': PriceRulesChannelsAtraveodeToJSON(value.bookeasycomau),
        'booking': PriceRulesChannelsAgodaToJSON(value.booking),
        'bookitconz': PriceRulesChannelsAtraveodeToJSON(value.bookitconz),
        'trip': PriceRulesChannelsAgodaToJSON(value.trip),
        'despegar': PriceRulesChannelsAgodaToJSON(value.despegar),
        'edreamsodigeo': PriceRulesChannelsAgodaToJSON(value.edreamsodigeo),
        'expedia': PriceRulesChannelsAgodaToJSON(value.expedia),
        'feratel': PriceRulesChannelsAgodaToJSON(value.feratel),
        'flipkey': PriceRulesChannelsAtraveodeToJSON(value.flipkey),
        'goibibo': PriceRulesChannelsAgodaToJSON(value.goibibo),
        'guestlinkcouk': PriceRulesChannelsAtraveodeToJSON(value.guestlinkcouk),
        'hometogo': PriceRulesChannelsAtraveodeToJSON(value.hometogo),
        'hostelinternational': PriceRulesChannelsAtraveodeToJSON(value.hostelinternational),
        'hostelsclub': PriceRulesChannelsAtraveodeToJSON(value.hostelsclub),
        'hostelworld': PriceRulesChannelsAgodaToJSON(value.hostelworld),
        'hotelbeds': PriceRulesChannelsAgodaToJSON(value.hotelbeds),
        'hrs': PriceRulesChannelsHrsToJSON(value.hrs),
        'jomres': PriceRulesChannelsAgodaToJSON(value.jomres),
        'lastminute': PriceRulesChannelsAgodaToJSON(value.lastminute),
        'marriott': PriceRulesChannelsAtraveodeToJSON(value.marriott),
        'ostrovokru': PriceRulesChannelsAgodaToJSON(value.ostrovokru),
        'ota': PriceRulesChannelsAgodaToJSON(value.ota),
        'reserva': PriceRulesChannelsAgodaToJSON(value.reserva),
        'tablethotels': PriceRulesChannelsAgodaToJSON(value.tablethotels),
        'tiket': PriceRulesChannelsAgodaToJSON(value.tiket),
        'tomastravel': PriceRulesChannelsAgodaToJSON(value.tomastravel),
        'traumferienwohnungen': PriceRulesChannelsAtraveodeToJSON(value.traumferienwohnungen),
        'traveloka': PriceRulesChannelsAgodaToJSON(value.traveloka),
        'travia': PriceRulesChannelsAgodaToJSON(value.travia),
        'tripadvisorrentals': PriceRulesChannelsAtraveodeToJSON(value.tripadvisorrentals),
        'vacationstay': PriceRulesChannelsAtraveodeToJSON(value.vacationstay),
        'vrbo': PriceRulesChannelsAtraveodeToJSON(value.vrbo),
        'webroomsconz': PriceRulesChannelsAtraveodeToJSON(value.webroomsconz),
    };
}

