/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertyRoomTypesInnerTextsInner
 */
export interface PropertyRoomTypesInnerTextsInner {
    /**
     * 
     * @type {string}
     * @memberof PropertyRoomTypesInnerTextsInner
     */
    language?: PropertyRoomTypesInnerTextsInnerLanguageEnum;
    /**
     * 
     * @type {string}
     * @memberof PropertyRoomTypesInnerTextsInner
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyRoomTypesInnerTextsInner
     */
    accommodationType?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyRoomTypesInnerTextsInner
     */
    roomDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyRoomTypesInnerTextsInner
     */
    auxiliary?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyRoomTypesInnerTextsInner
     */
    marketing?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyRoomTypesInnerTextsInner
     */
    contentHeadline?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyRoomTypesInnerTextsInner
     */
    contentDescription?: string;
}


/**
 * @export
 */
export const PropertyRoomTypesInnerTextsInnerLanguageEnum = {
    En: 'en',
    Ar: 'ar',
    Bg: 'bg',
    Ca: 'ca',
    Cs: 'cs',
    Da: 'da',
    De: 'de',
    El: 'el',
    Es: 'es',
    Et: 'et',
    Fi: 'fi',
    Fr: 'fr',
    Hr: 'hr',
    He: 'he',
    Hu: 'hu',
    Id: 'id',
    Is: 'is',
    It: 'it',
    Ja: 'ja',
    Ko: 'ko',
    Lt: 'lt',
    Mn: 'mn',
    My: 'my',
    Nl: 'nl',
    No: 'no',
    Pl: 'pl',
    Pt: 'pt',
    Ro: 'ro',
    Ru: 'ru',
    Sk: 'sk',
    Sl: 'sl',
    Sr: 'sr',
    Sv: 'sv',
    Th: 'th',
    Tr: 'tr',
    Vi: 'vi',
    Zh: 'zh',
    Zt: 'zt'
} as const;
export type PropertyRoomTypesInnerTextsInnerLanguageEnum = typeof PropertyRoomTypesInnerTextsInnerLanguageEnum[keyof typeof PropertyRoomTypesInnerTextsInnerLanguageEnum];


/**
 * Check if a given object implements the PropertyRoomTypesInnerTextsInner interface.
 */
export function instanceOfPropertyRoomTypesInnerTextsInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PropertyRoomTypesInnerTextsInnerFromJSON(json: any): PropertyRoomTypesInnerTextsInner {
    return PropertyRoomTypesInnerTextsInnerFromJSONTyped(json, false);
}

export function PropertyRoomTypesInnerTextsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyRoomTypesInnerTextsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'language': !exists(json, 'language') ? undefined : json['language'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'accommodationType': !exists(json, 'accommodationType') ? undefined : json['accommodationType'],
        'roomDescription': !exists(json, 'roomDescription') ? undefined : json['roomDescription'],
        'auxiliary': !exists(json, 'auxiliary') ? undefined : json['auxiliary'],
        'marketing': !exists(json, 'marketing') ? undefined : json['marketing'],
        'contentHeadline': !exists(json, 'contentHeadline') ? undefined : json['contentHeadline'],
        'contentDescription': !exists(json, 'contentDescription') ? undefined : json['contentDescription'],
    };
}

export function PropertyRoomTypesInnerTextsInnerToJSON(value?: PropertyRoomTypesInnerTextsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'language': value.language,
        'displayName': value.displayName,
        'accommodationType': value.accommodationType,
        'roomDescription': value.roomDescription,
        'auxiliary': value.auxiliary,
        'marketing': value.marketing,
        'contentHeadline': value.contentHeadline,
        'contentDescription': value.contentDescription,
    };
}

