/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertyPaymentGatewaysStripe
 */
export interface PropertyPaymentGatewaysStripe {
    /**
     * 
     * @type {string}
     * @memberof PropertyPaymentGatewaysStripe
     */
    type?: PropertyPaymentGatewaysStripeTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof PropertyPaymentGatewaysStripe
     */
    priority?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PropertyPaymentGatewaysStripe
     */
    saveAllCards?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PropertyPaymentGatewaysStripe
     */
    capture?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PropertyPaymentGatewaysStripe
     */
    checkoutVersion?: PropertyPaymentGatewaysStripeCheckoutVersionEnum;
    /**
     * 
     * @type {string}
     * @memberof PropertyPaymentGatewaysStripe
     */
    paymentDescription?: string;
}


/**
 * @export
 */
export const PropertyPaymentGatewaysStripeTypeEnum = {
    Enable: 'enable',
    Disable: 'disable',
    Internal: 'internal'
} as const;
export type PropertyPaymentGatewaysStripeTypeEnum = typeof PropertyPaymentGatewaysStripeTypeEnum[keyof typeof PropertyPaymentGatewaysStripeTypeEnum];

/**
 * @export
 */
export const PropertyPaymentGatewaysStripeCheckoutVersionEnum = {
    Embedded: 'embedded',
    Hosted: 'hosted'
} as const;
export type PropertyPaymentGatewaysStripeCheckoutVersionEnum = typeof PropertyPaymentGatewaysStripeCheckoutVersionEnum[keyof typeof PropertyPaymentGatewaysStripeCheckoutVersionEnum];


/**
 * Check if a given object implements the PropertyPaymentGatewaysStripe interface.
 */
export function instanceOfPropertyPaymentGatewaysStripe(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PropertyPaymentGatewaysStripeFromJSON(json: any): PropertyPaymentGatewaysStripe {
    return PropertyPaymentGatewaysStripeFromJSONTyped(json, false);
}

export function PropertyPaymentGatewaysStripeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyPaymentGatewaysStripe {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'priority': !exists(json, 'priority') ? undefined : json['priority'],
        'saveAllCards': !exists(json, 'saveAllCards') ? undefined : json['saveAllCards'],
        'capture': !exists(json, 'capture') ? undefined : json['capture'],
        'checkoutVersion': !exists(json, 'checkoutVersion') ? undefined : json['checkoutVersion'],
        'paymentDescription': !exists(json, 'paymentDescription') ? undefined : json['paymentDescription'],
    };
}

export function PropertyPaymentGatewaysStripeToJSON(value?: PropertyPaymentGatewaysStripe | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'priority': value.priority,
        'saveAllCards': value.saveAllCards,
        'capture': value.capture,
        'checkoutVersion': value.checkoutVersion,
        'paymentDescription': value.paymentDescription,
    };
}

