/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StripeAddPaymentMethodCard } from './StripeAddPaymentMethodCard';
import {
    StripeAddPaymentMethodCardFromJSON,
    StripeAddPaymentMethodCardFromJSONTyped,
    StripeAddPaymentMethodCardToJSON,
} from './StripeAddPaymentMethodCard';

/**
 * 
 * @export
 * @interface StripeAddPaymentMethod
 */
export interface StripeAddPaymentMethod {
    /**
     * 
     * @type {string}
     * @memberof StripeAddPaymentMethod
     */
    action?: string;
    /**
     * 
     * @type {number}
     * @memberof StripeAddPaymentMethod
     */
    bookingId?: number;
    /**
     * 
     * @type {StripeAddPaymentMethodCard}
     * @memberof StripeAddPaymentMethod
     */
    card?: StripeAddPaymentMethodCard;
}

/**
 * Check if a given object implements the StripeAddPaymentMethod interface.
 */
export function instanceOfStripeAddPaymentMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StripeAddPaymentMethodFromJSON(json: any): StripeAddPaymentMethod {
    return StripeAddPaymentMethodFromJSONTyped(json, false);
}

export function StripeAddPaymentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripeAddPaymentMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': !exists(json, 'action') ? undefined : json['action'],
        'bookingId': !exists(json, 'bookingId') ? undefined : json['bookingId'],
        'card': !exists(json, 'card') ? undefined : StripeAddPaymentMethodCardFromJSON(json['card']),
    };
}

export function StripeAddPaymentMethodToJSON(value?: StripeAddPaymentMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'bookingId': value.bookingId,
        'card': StripeAddPaymentMethodCardToJSON(value.card),
    };
}

