/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhooksBookingsPostRequestBookingBookingGroup
 */
export interface WebhooksBookingsPostRequestBookingBookingGroup {
    /**
     * 
     * @type {number}
     * @memberof WebhooksBookingsPostRequestBookingBookingGroup
     */
    master?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof WebhooksBookingsPostRequestBookingBookingGroup
     */
    ids?: Array<number>;
}

/**
 * Check if a given object implements the WebhooksBookingsPostRequestBookingBookingGroup interface.
 */
export function instanceOfWebhooksBookingsPostRequestBookingBookingGroup(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WebhooksBookingsPostRequestBookingBookingGroupFromJSON(json: any): WebhooksBookingsPostRequestBookingBookingGroup {
    return WebhooksBookingsPostRequestBookingBookingGroupFromJSONTyped(json, false);
}

export function WebhooksBookingsPostRequestBookingBookingGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhooksBookingsPostRequestBookingBookingGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'master': !exists(json, 'master') ? undefined : json['master'],
        'ids': !exists(json, 'ids') ? undefined : json['ids'],
    };
}

export function WebhooksBookingsPostRequestBookingBookingGroupToJSON(value?: WebhooksBookingsPostRequestBookingBookingGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'master': value.master,
        'ids': value.ids,
    };
}

