/* tslint:disable */
/* eslint-disable */
/**
 * API V2
 * For more information see [wiki.beds24.com/index.php/API_V2.0](https://wiki.beds24.com/index.php/API_V2.0)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InvoiceItem } from './InvoiceItem';
import {
    InvoiceItemFromJSON,
    InvoiceItemFromJSONTyped,
    InvoiceItemToJSON,
} from './InvoiceItem';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';
import type { WebhooksBookingsPostRequestBooking } from './WebhooksBookingsPostRequestBooking';
import {
    WebhooksBookingsPostRequestBookingFromJSON,
    WebhooksBookingsPostRequestBookingFromJSONTyped,
    WebhooksBookingsPostRequestBookingToJSON,
} from './WebhooksBookingsPostRequestBooking';
import type { WebhooksBookingsPostRequestInfoItemsInner } from './WebhooksBookingsPostRequestInfoItemsInner';
import {
    WebhooksBookingsPostRequestInfoItemsInnerFromJSON,
    WebhooksBookingsPostRequestInfoItemsInnerFromJSONTyped,
    WebhooksBookingsPostRequestInfoItemsInnerToJSON,
} from './WebhooksBookingsPostRequestInfoItemsInner';

/**
 * 
 * @export
 * @interface WebhooksBookingsPostRequest
 */
export interface WebhooksBookingsPostRequest {
    /**
     * 
     * @type {Date}
     * @memberof WebhooksBookingsPostRequest
     */
    timeStamp?: Date;
    /**
     * 
     * @type {WebhooksBookingsPostRequestBooking}
     * @memberof WebhooksBookingsPostRequest
     */
    booking?: WebhooksBookingsPostRequestBooking;
    /**
     * 
     * @type {Array<WebhooksBookingsPostRequestInfoItemsInner>}
     * @memberof WebhooksBookingsPostRequest
     */
    infoItems?: Array<WebhooksBookingsPostRequestInfoItemsInner>;
    /**
     * 
     * @type {Array<InvoiceItem>}
     * @memberof WebhooksBookingsPostRequest
     */
    invoiceItems?: Array<InvoiceItem>;
    /**
     * 
     * @type {Array<Message>}
     * @memberof WebhooksBookingsPostRequest
     */
    messages?: Array<Message>;
    /**
     * 
     * @type {number}
     * @memberof WebhooksBookingsPostRequest
     */
    retries?: number;
}

/**
 * Check if a given object implements the WebhooksBookingsPostRequest interface.
 */
export function instanceOfWebhooksBookingsPostRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WebhooksBookingsPostRequestFromJSON(json: any): WebhooksBookingsPostRequest {
    return WebhooksBookingsPostRequestFromJSONTyped(json, false);
}

export function WebhooksBookingsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhooksBookingsPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timeStamp': !exists(json, 'timeStamp') ? undefined : (new Date(json['timeStamp'])),
        'booking': !exists(json, 'booking') ? undefined : WebhooksBookingsPostRequestBookingFromJSON(json['booking']),
        'infoItems': !exists(json, 'infoItems') ? undefined : ((json['infoItems'] as Array<any>).map(WebhooksBookingsPostRequestInfoItemsInnerFromJSON)),
        'invoiceItems': !exists(json, 'invoiceItems') ? undefined : ((json['invoiceItems'] as Array<any>).map(InvoiceItemFromJSON)),
        'messages': !exists(json, 'messages') ? undefined : ((json['messages'] as Array<any>).map(MessageFromJSON)),
        'retries': !exists(json, 'retries') ? undefined : json['retries'],
    };
}

export function WebhooksBookingsPostRequestToJSON(value?: WebhooksBookingsPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timeStamp': value.timeStamp === undefined ? undefined : (value.timeStamp.toISOString()),
        'booking': WebhooksBookingsPostRequestBookingToJSON(value.booking),
        'infoItems': value.infoItems === undefined ? undefined : ((value.infoItems as Array<any>).map(WebhooksBookingsPostRequestInfoItemsInnerToJSON)),
        'invoiceItems': value.invoiceItems === undefined ? undefined : ((value.invoiceItems as Array<any>).map(InvoiceItemToJSON)),
        'messages': value.messages === undefined ? undefined : ((value.messages as Array<any>).map(MessageToJSON)),
        'retries': value.retries,
    };
}

